### ISSUE TITLE
attach ajax autocomplete

### ISSUE THREAD

**Issue by dansabirov** [handsontable/ngHandsontable#1]
Hi, @warpech 

Is there any way attach ajax complete to angular-ui-handsontable?

I tried, but without success.

**Comment by nicholasmabrams** [comment]
This is a feature that would be easy to pull off in the normal Handsontable, could we get the ability here as well?

**Comment by AMBudnik** [comment]
Sorry for a delay. However, I do not have any useful projects/scripts that I can recommend. The only way that sounds reasonable is to create a custom editor
