### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by sangd** [handsontable/ngHandsontable#100]
Do you have any plan for Angular 2 support? Even though Angular 2 current stage is Developer Preview, it looks like it'll be available some time soon.

**Comment by pmig** [comment]
Hi @sangd 

I found https://github.com/valor-software/ng2-handsontable. 

Sadly they are based on an angular2 alpha version not supporting the current angular2.beta.13.

I already opened a ticket over there:
https://github.com/valor-software/ng2-handsontable/issues/69

Maybe @budnix can give us some details related to the ngHandsontable and Angular2

**Comment by AMBudnik** [comment]
Hi @sangd and @pmig 
Today we had a bigger meeting about our plans for Q2 and Q3 and we're planning to add Angular 2 support in Q3. Currently there's a lot of time to rethink our priorities for Q3 but Angular 2 is one of our solid ideas.

**Comment by harunurhan** [comment]
Hi @AMBudnik 

What is current status of Angular 2 support?

**Comment by AMBudnik** [comment]
Hi @harunurhan 
Unfortunately it's still in the 'idea' zone. You can track our Roadmap for updates: https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features (also you can vote for features if you have a trello account).

**Comment by valorkin** [comment]
We have started to update to ng2 RC, but stack with resolving decencies for handsometable

**Comment by valorkin** [comment]
If needed I can transfer our ng2 repo to ng2 org and give you admin access, and access to npm

**Comment by AMBudnik** [comment]
Please go to https://github.com/handsontable/angular-handsontable for a Angular 2+ wrapper
