### ISSUE TITLE
Use this inside another directive

### ISSUE THREAD

**Issue by crash21** [handsontable/ngHandsontable#102]
Hello,

I am using ngHandsometables and angular.

In the first example here

http://jsfiddle.net/bgdhpxeL/6/

Things are working fine. scope.grid object which has all the data needed to feed the grid are passed to the grid and 2 way binding works fine (data in the top changes if you change a cell).

Now in this example here

http://jsfiddle.net/4rfxjbqc/14/

I created a customDirective and inside this directive which has isolated scope and without using any controller I embed a template which uses directive inside. Code inside link method is same with code in previous controller and also data outputted before table definition has the same data. Everything seems fine but somehow the scope don't get the grid.datarows object... In some debugging I have done the scope.datarows inside handsometables directive is undefined.

Any idea why this is happening? What I am doing wrong? I just need to use a custom directive with isolated scope and inside this one embed another directive and pass data to it.

Thanks a lot.

**Comment by crash21** [comment]
Anyone can help me on this?

**Comment by crash21** [comment]
Still no solution for this?

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
