### ISSUE TITLE
onAfterChange is called twice for each change.

### ISSUE THREAD

**Issue by Saint-Fiasco** [handsontable/ngHandsontable#106]
Playing around with this demo http://handsontable.github.io/ngHandsontable/demo/#/callbacks-callbacks-by-object

I noticed that if I add the following callback:

    onAfterChange: function() {
      console.log('onAfterChange call');
    }

Every time I modify a cell, 'onAfterChange call' is printed on the console twice.

**Comment by Saint-Fiasco** [comment]
This works correctly on this other demo: http://handsontable.github.io/ngHandsontable/demo/#/callbacks-callbacks-declarative-way

This bug occurs only when the callback is done via the settings object.

**Comment by budnix** [comment]
Yes, you're right this is a bug.
