### ISSUE TITLE
Rendering custom HTML in header

### ISSUE THREAD

**Issue by andreabenitez** [handsontable/ngHandsontable#107]
Handsontable lets me add a checkbox to the column header title with "Handsontable.Dom.addEvent" (http://docs.handsontable.com/0.17.0/demo-custom-renderers.html), is there a way to do this with ngHandsontable? I haven't found this funcionality in the last ngHandsontable demo.

**Comment by budnix** [comment]
Hi, Yes custom renderers are working to in ngHandsontable version. I prepared working demo here http://jsfiddle.net/39oeyjzz/.
