### ISSUE TITLE
release notes for 0.7.0-beta1 incorrect regarding hyphen s

### ISSUE THREAD

**Issue by richtier** [handsontable/ngHandsontable#110]
Release notes read "Attributes defined in camelCase style will no longer be supported."

However, `getAvailableSettings` only hypenatenates if the argument `hyphenateStyle` is true. `hyphenateStyle` is never true because `applyAvailableSettingsScopeDef` and `mergeSettingsFromScope` calls `getAvailableSettings()` rather than `getAvailableSettings(true)`.

**Comment by budnix** [comment]
Angular automatically converts attributes defined in hyphenate style into camelCase style so that way settingsFactory still operates in second style.
