### ISSUE TITLE
Pagination with ngHandsontable

### ISSUE THREAD

**Issue by deenairn** [handsontable/ngHandsontable#111]
I'm new to Angular and trying out the Angular wrapper for a new project I'm working on. Previously it was very easy to use pagination use the # links as per the demo on the main site:

http://docs.handsontable.com/0.17.0/demo-pagination.html

What would be the most practical way to replicate this behaviour with ngHandsontable?

**Comment by budnix** [comment]
Hi, pagination demo for ngHandsontable you can find at http://handsontable.github.io/ngHandsontable/demo/#/pagination-columns-pagination

**Comment by deenairn** [comment]
Brilliant thanks Alexandra, was going to supply my own sample using Bootstrap pagination once I had figured out how I wanted to get it to work. I think your example is better for a project based example as it does not include as many external dependencies. Thanks for responding so quickly.
