### ISSUE TITLE
IE11 Problem with Context Menu 0.7.0-beta1

### ISSUE THREAD

**Issue by deenairn** [handsontable/ngHandsontable#112]
I've noticed a JavaScript error coming from the callbackProxy callback within handsontable which does not appear in Firefox or Chrome. 

Plunk below highlights the issue

http://plnkr.co/edit/wmh7SXduRCnR9UDFQqpj?p=preview

![ie11](https://cloud.githubusercontent.com/assets/3931242/9740126/fb584f34-564a-11e5-9526-d554c1c523b2.png)

**Comment by deenairn** [comment]
Have you had any luck looking at this defect? I only ask as it was added to 0.7.0-beta2 milestone which was yesterday.

**Comment by budnix** [comment]
This bug was fixed in Handsontable repository. New Handsontable version has been released couple hours ago, ngHandsontable will be released tomorrow.
