### ISSUE TITLE
All Rows selection

### ISSUE THREAD

**Issue by homi2015** [handsontable/ngHandsontable#113]
Is there a way to select all rows in the Handsontable like the ones which are present in other common grids (like UI grid -  http://ui-grid.info/docs/#/tutorial/210_selection ) ?

**Comment by budnix** [comment]
Yes it's possible to select all rows. I prepared working demo at http://jsbin.com/kizeyumepa/edit.

**Comment by homi2015** [comment]
@budnix - Thanks a lot for such a quick response. The sample example you provided is great.

However, I was looking into something like the following where I will have checkboxes in the row headers and have more control on the rows I'm selecting. Additionally if I want to select all rows, I should be able to provide a checkbox at the header (like the one you have provided in http://jsfiddle.net/39oeyjzz/ ) and select all the rows

See my sample plunker

http://plnkr.co/edit/cFod6udGg8jAKD2SwZP7?p=preview

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
