### ISSUE TITLE
Killing performance of entire app

### ISSUE THREAD

**Issue by chrisfid** [handsontable/ngHandsontable#116]
I recently added ngHandsontable to my large SPA under the impression that it performed very well. But the rest of my app suffers significantly with Handsontable active.

Here is CPU profile without Handsontable active:
![without_handsontable](https://cloud.githubusercontent.com/assets/7884955/10119867/ca3e017c-6479-11e5-88fc-85ea35465b93.png)

Now here it is with Handsontable active (performing the same activity):
![with_handsontable](https://cloud.githubusercontent.com/assets/7884955/10119868/d12c6802-6479-11e5-8fe8-4b698cf227d1.png)

What I am profiling has *nothing to do with Handsontable* apart from the fact that they are loaded on the same page. And it is not a watching issue, as I know ngHandsontable does deep watching but I can disable that with the same outcome (as well as verify it in Chrome's Angular Batarang).

So what is going on here? Handsontable has slowed down my app by orders of magnitude for no good reason (from my perspective). Is this a known issue? How has it been addressed in the past?

**Comment by chrisfid** [comment]
Closing this as a combo of changes helped me speed things up, in case it helps someone:
- updating version of ng/Handsontable
- fixed column widths
- no deep watching of collection (had to modify source)
- manually destroy Handsontable instance as needed
- optimize cell renderer heavily

Though it still bothers me how Handsontable manages to add such overhead to 'irrelevant' events.

**Comment by motin** [comment]
> no deep watching of collection (had to modify source)

Care to share you modifications?

**Comment by motin** [comment]
> I am using 7.0-beta1 and the performance is completely terrible. Handsontable itself is designed for great performance, but ngHandsontable certainly is not. Until this has changed, or there is a documented way around this, I'd let this issue remain open.

Update: I wrote an alternative, simpler, directive for handsontable angular integration and the performance is now much much better: https://github.com/neam/angular-simple-handsontable

**Comment by budnix** [comment]
Hi, If you want to exclude your data from watching you can use `<hot-table settings="ctrl.settings">` attribute which is as the only one excluded from watching. This solution should increase ngHandsontable performance.

**Comment by budnix** [comment]
Additionally you can try to use the newest version of ngHandsontable 0.7.0 where some improvements was added.

**Comment by motin** [comment]
> Hi, If you want to exclude your data from watching you can use <hot-table settings="ctrl.settings"> attribute which is as the only one excluded from watching. This solution should increase ngHandsontable performance.

Thanks, but two-way data binding is essential to our application. It works thanks to a two-way data-binding and a single watch in [angular-simple-handsontable](https://github.com/neam/angular-simple-handsontable). Demo: http://jsbin.com/vareba/edit?html,js,output

> Additionally you can try to use the newest version of ngHandsontable 0.7.0 where some improvements was added.

I don't think I am going back for a while after having just migrated to angular-simple-handsontable, but a great tip for existing ngHandsontable users, always great with improvements! :)

**Comment by chrisfid** [comment]
@motin I don't really have any applicable code to share. I just removed the deep watching part of ngHandsontable, and using the (somewhat hacky) solution from #34 got the instance and just called the API update methods myself as needed (not sure if I should have even been using this module - no offense intended).

But in general my performance issues were not primarily related to ngHandsontable, but Handsontable itself. For me it was that Handsontable seemed to be hooking into/wrapping (?) events globally (just speculation as I have not read Handsontable code) and adding a tonne of overhead (probably due to my complex cell rendering).

But that still pisses me off. I see Handsontable adding overhead on events that could/should not possibly affect Handsontable.
