### ISSUE TITLE
changes / enhancement of autoCompleteFactory.js

### ISSUE THREAD

**Issue by sandro-heitz** [handsontable/ngHandsontable#117]
Let me first thank you for your work. I think that it is really well done and that you have brought handsontable to angular in an elegant way. 

But I had some problems with the "autcomplete" type and I want to propose the following changes to the existing source code. 

Let me show you at first the existing source code and a possible usage: 

**autoCompleteFactory.js**

``` javascript
var options = column.optionList;

if (!option.object) {
  return;
}
```

You can use it like this: 

``` javascript
{
  width: 100,
  data: 'unit',
  type: 'autocomplete',
  strict: true,
  allowInvalid: true,
  optionList: { object: ['mm', 'cm', 'm', 'km']}
  // ... and so one
```

Let me describe my use case: I wanted to generate option lists depending on the data of the row and I had the need to generate options list via a server call: 

I have changed  **autoCompleteFactory.js**

``` javascript
  var options = column.optionList;
  if (column.dynamicList) {
    column.dynamicList(data, query, process);
    return;
}

  if (!options.object) {
    return;
  }
```

And can now use it like this (without having changed or broken the "old" usage pattern): 

``` javascript
  {
   width: 100,
   data: 'unit',
   type: 'autocomplete',
   //optionList: { object: ['mm', 'cm', 'm', 'km' ] },
   dynamicList: function(data, query, process) {
    if (query && query.length < 3) {
      // I do not want to build a request, when the user has typed just on character 
     // i let handsontable process an empty array to avoid broken editor cell 
      process([]);
      return;
    }
    // here is the call ... 
    // query could be included ... 
    $http.get('data/data.json').then(function(response) {
      process(response.data.found);
    });
   },
   strict: true,
   allowInvalid: true
   },
```

Or I can use it like this: 

``` javascript
  {
   width: 100,
   data: 'unit',
   type: 'autocomplete',
   //optionList: { object: ['mm', 'cm', 'm', 'km' ] },
   dynamicList: function(data, query, process) {
     process(data.units); 
   },
   strict: true,
   allowInvalid: true
   },
```

And again: thank you very much!

**Comment by sandro-heitz** [comment]
The check of the query parameter must be like: 
```javascript
    if (!query || query.length < 3) {
    // and so on ..
```

**Comment by budnix** [comment]
Hi, thanks for interesting thoughts but after investigation I decided to keep syntax similar to Handsontable [source property](http://docs.handsontable.com/0.19.0/Options.html#source). This property is working very similar to your idea. I prepared a demo for you [here](http://jsbin.com/wuporodaju/edit?html,js,output).
