### ISSUE TITLE
Slow Performance : Taking more than 3 seconds to update

### ISSUE THREAD

**Issue by surya2312** [handsontable/ngHandsontable#120]
Hello Everyone,

I am using ngHandsontable and handson.formula.js.
I am construction an Excel like table with 500 rows and 60 columns .
Every cell in (rowNumber%10) is sum of 9 cells below that.
Every first cell in each row is sum of all cells in that row.
I am  constructing the Excel formula for Sum ( =SUM(startCell : endCell) ).

The problem is when update a cell , it is taking very long time to update the Sum Feilds.

Please suggest. If any other alternative approach. 
Highlighting Cells with Formula.

![sum](https://cloud.githubusercontent.com/assets/14157260/10213663/9f41507a-682d-11e5-8e38-77eed81d128a.jpg)

Regards,
Surya Prasad.

**Comment by AMBudnik** [comment]
For all users who have performance issues please read https://docs.handsontable.com/pro/1.17.0/tutorial-performance-tips.html

Also, try to:
- use server-side pagination
- set height and width for the table
- use higher rows and wider columns if possible
