### ISSUE TITLE
Paging and setting grid height question

### ISSUE THREAD

**Issue by s-aravind** [handsontable/ngHandsontable#122]
Hello there,  I'm new to Angular and Handsontable.  I have successfully incorporated the ngHandsontable grid in my project and also it is displaying data.  

Could you please help me understand how to set paging feature and also how to set grid height from Angular code (run time).  I noticed when i change the height value at run time the data in the grid disappears.

Thank you in Advance.

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
