### ISSUE TITLE
Custom attribute not working

### ISSUE THREAD

**Issue by sivapgv** [handsontable/ngHandsontable#123]
Hi,

I am using custom attribute in hot column like below. But in latest nghandsontable version not working. please fix it or any update on this? Before it working properly in nghandsontable version 6.

 <hot-column data='column1' title="'Total premium'" type="'numeric'" numberdigit="'17'" decimaldigit="'3'" format="'0,0'"  read-only="'true'"></hot-column>

I am analyzed in handsontable.js file and update below code line no :422, then its working fine.

angular.forEach(Object.keys(attrs), function(key) {
            if (key.charAt(0) !== '$' && typeof attrs[key] !== 'undefined') {
              if (key === 'data') {
                  column['data'] = attrs[key];
                } else {
                  column[key] = scope.$eval(attrs[key]);
                }
            }
          });

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
