### ISSUE TITLE
Handsontable version 0.20

### ISSUE THREAD

**Issue by jromero-onclick** [handsontable/ngHandsontable#124]
Hello

Are you going to update the library to be compatible with the handsontable 0.20?
I have seen that there are important changes related to the countRows and the getData methods.

Thank you

**Comment by opticyclic** [comment]
v0.22 is available now. https://github.com/handsontable/handsontable/releases

**Comment by AMBudnik** [comment]
ngHandsontable now updated to Handsontable 0.22.0 with v[0.8.0](https://github.com/handsontable/ngHandsontable/releases/tag/0.8.0)

**Comment by estvmachine** [comment]
Thanks!
