### ISSUE TITLE
How to Check conditions before delete rows using Context Menu delete row

### ISSUE THREAD

**Issue by sambsa** [handsontable/ngHandsontable#127]
I am using contextMenu to delete Rows. Is there any event that I can handle certain checks before delete?

I mean if I click Delete Row after selecting rows then it should check the rows before delete, suppose if a column suppose 1st column contains value 0 then it should not delete while other rows must delete.

`function DeleteRow(){
  for(){ //iterate all rows 
   // get first column 
    if(column value == 0){
       do not delete
    }
   else{
      //Delete
    }
 }
}`

I am expecting something like above if I click that context menu row delete. 

How can I achieve this?

Thanks in Advance!!

**Comment by AMBudnik** [comment]
Hi @sambsa you can use [`beforeRemoveRow`](http://docs.handsontable.com/0.19.0/Hooks.html#event:beforeRemoveRow)
Callback is fired when one or more rows are about to be removed.
