### ISSUE TITLE
When a new object of equal value is assigned to the object containing the handsontable datarows the binding with the object is lost

### ISSUE THREAD

**Issue by deenairn** [handsontable/ngHandsontable#128]
I have a scenario where I have an object that is bound to the hot table. This value may be updated as a consequence of a REST API call and re-assigned - however this value may be equal. In our example, the table is bound to a portion of an object and this portion of the object may not have changed but the object is a new reference as it has been re-assigned. In this case, because the object is equal - but not reference equal - the datarows / data source is not updated to the new value. Therefore any further edits are not tracked - and if a PUT is performed with updates applied to the table - then these will not be sent to the REST API and therefore the changes lost.

To replicate this situation I have created the following plunk. There is a "Refresh" button which is used to emulate the REST call initializaing a new object. The table above shows the data returned from the method, with hot table below showing the same data (in theory at least).

Scenario 1, perform edits and watch the table above change at the same time as nghandsontable.

Scenario 2, immediately press the Refresh button. This emulates what happens for us when the REST server retrieving an object which is equal. Now edit the hot table below. You will notice that they are now out of synch and changes applied to the hot table will not be applied to the table above.

http://plnkr.co/edit/iLFmfN?p=preview

**Comment by deenairn** [comment]
This fix for this is quite easy and if I will attempt to create a Pull Request for it:

http://plnkr.co/edit/Zlp7xA?p=preview

Essentially the 'datarows' watch must be excluded from the list ['datarows', 'columns', 'rowHeights', 'colWidths', 'rowHeaders', 'colHeaders'] to ensure a reference equality check is done.

**Comment by yinyihui** [comment]
I find out another way to fix this problem much like your solution, plz check the issue:
https://github.com/handsontable/ngHandsontable/issues/141#issuecomment-278554572
