### ISSUE TITLE
Publish as npm request

### ISSUE THREAD

**Issue by datLucius** [handsontable/ngHandsontable#130]
Please publish as npm module if possible. I am not able to use bower with the current project I am working on. Thanks for all the work thus far on ngHandsontable!

**Comment by jlsalmon** [comment]
Same here. We are in fact switching to npm everywhere, since bower development has been stopped.

**Comment by mnmercer** [comment]
+1 We really need this as a npm module as my project cannot use bower either. It looks like a fantastic project and I'd love to be able to utilize it!

**Comment by DaHaiz** [comment]
**+1 please publish as npm module!** cant use bower...

**Comment by budnix** [comment]
Hi folks!, I've released ngHandsontable to 0.13.0 which includes the newest version of Handsontable. Since this version every new release will be published into npm repository (including this one).
