### ISSUE TITLE
Can't Seem To Use $scope

### ISSUE THREAD

**Issue by opticyclic** [handsontable/ngHandsontable#131]
See this plunker for an example of ngHandsontable working with the this keyword
http://plnkr.co/edit/GPYTdJ?p=preview

Note how I had to do `var that = this;` in order to access the models inside a function as the definition of `this` changes.

If you replace all the occurrences of `this` with `$scope` the grid doesn't populate with data at all.

Why can't I use the $scope variable for the model?

**Comment by homi2015** [comment]
You can use scope variables in your model. Check the plunker here
[scope usage](http://plnkr.co/edit/pr4CYf?p=preview)

Ensure that you inject the $scope in your controller
