### ISSUE TITLE
Unable to update custom borders

### ISSUE THREAD

**Issue by homi2015** [handsontable/ngHandsontable#137]
Hello,

I have been trying to update customBorders through the method updateSettings, but it doesn't work. If the customBorder values are provided at the very beginning when the hot table settings are defined then it works fine. Later when we try to update, it doesn't work. Please find below the plunker

http://plnkr.co/edit/ARzGTPbqbpdWNBOOvqVN?p=preview

Let me know if there's any workaround.

**Comment by AMBudnik** [comment]
Hi @homi2015 it's an issue from Handsontable https://github.com/handsontable/handsontable/issues/2002

**Comment by AMBudnik** [comment]
I am closing this issue. Please track updates to https://github.com/handsontable/handsontable/issues/2002
