### ISSUE TITLE
Adding comments programatically

### ISSUE THREAD

**Issue by estvmachine** [handsontable/ngHandsontable#138]
Hi, i do this example: http://jsbin.com/nidaqog/1/edit?. Here i show when you try to add comments programatically dont really add the comment only show the window of comments. For do this i mix the code for add Comments of hansonTable and the theory of obtain instance of HotTable in ngHansontable: 
- https://docs.handsontable.com/0.22.0/Comments.html
- http://handsontable.github.io/ngHandsontable/demo/#/other-access-to-instance

**Comment by oshri551** [comment]
Hi,
I have a workaround for you.
replace the code:
commentsPlugin.editor.setValue('Comment text');
with:
hotInstance.getCellMeta(1, 2).comment = "some comment";
