### ISSUE TITLE
onBeforeColumnSort

### ISSUE THREAD

**Issue by benjamingarcia** [handsontable/ngHandsontable#140]
- Like  on `onAfterChange` callback it can be usefull for `onBeforeColumnSort`  to send column variable name with column index. 
- Instead of boolean, `amount` can be `ASC`, `DESC`, `NONE`?

**Comment by Wh1t3L0tus** [comment]
+1

**Comment by AMBudnik** [comment]
The hook has been added https://docs.handsontable.com/pro/1.17.0/Hooks.html#event:beforeColumnSort
