### ISSUE TITLE
How refresh data after server call?

### ISSUE THREAD

**Issue by benjamingarcia** [handsontable/ngHandsontable#141]
When I sort with server side, data aren't updated. If I call render() method on instance, I loose `sortIndicator`.
So How I refesh data without render() call?

:sos:

**Comment by homi2015** [comment]
Declare a hot-id inside hot-table tag and through the "hotRegisterer" (you need to inject that in your controller) get an handle of the hot-table instance from the hot-id. After that use the loadData function from the instance to refresh the grid with your new data. Below is a snippet provided:

`MainCtrl.$inject = ['$http','hotRegisterer']`

```
$http.get('../data/zips.json').success(function(data){ 
        hotRegisterer.getInstance('my-handsontable').loadData(data);
      }).error(function(msg,code){
        console.log(msg);
      });  
```
```
<hot-table
    hot-id="my-handsontable"
    settings="ctrl.settings"
    row-headers="ctrl.rowHeaders"
    col-headers="ctrl.colHeaders"
    datarows="ctrl.db.items"
    >
  </hot-table>
```

**Comment by garypma** [comment]
I'm having the same issue, and I have tried to loadData with no success. After the ajax call it, loads the results, but only 5 rows are shown until I click on any cell in the table. The only workaround I have found so far was to seed the result set for the table with an empty array the size of data I'm expecting back from the sever like so:

            $scope.dataTable = [];
            for (var i = 0; i < number; i++) {
                $scope.dataTable .push({});
            }

Once I do this the Table renders correctly with all the results I expect, even if I get back less than expected. Anyway, maybe this will help someone else not go through hours of pain like I did.

**Comment by compwright** [comment]
Sounds like a bug in loadData() or refresh() to me... @budnix can we get this fixed? I'm running into the same issue and pushing extra rows based on the expected response is not going to be very maintainable.

**Comment by garypma** [comment]
I agree, this solution isn't a good one. Actually after thinking about it all you need to do is do $scope.dataTable.length = number
Still, it's a bit of a hack and your right, not very maintainable.

**Comment by yinyihui** [comment]
I get the same issue and find out that the watchers code like this:
// TODO: Add watch properties descriptor + needs perf test. Watch full equality vs toJson
          angular.forEach(bindingsKeys, function(key) {
            scope.$watch(key, function(newValue, oldValue) {
              if (newValue === void 0) {
                return;
              }
              if (key === 'datarows') {
                // If reference to data rows is not changed then only re-render table
                if (scope.hotInstance.getSettings().data === newValue) {
                  settingFactory.renderHandsontable(scope.hotInstance);
                } else {
                  scope.hotInstance.loadData(newValue);
                  scope.htSettings.data = newValue;
                }
              } else if (newValue !== oldValue) {
                scope.htSettings[key] = newValue;
                settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
              }
            }, ['datarows', 'columns', 'rowHeights', 'colWidths', 'rowHeaders', 'colHeaders'].indexOf(key) >= 0);
          });
if datarows changed not only the data length, but also the data column, you may have to add:
    settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
after the datarows branch like this:
// TODO: Add watch properties descriptor + needs perf test. Watch full equality vs toJson
          angular.forEach(bindingsKeys, function(key) {
            scope.$watch(key, function(newValue, oldValue) {
              if (newValue === void 0) {
                return;
              }
              if (key === 'datarows') {
                // If reference to data rows is not changed then only re-render table
                if (scope.hotInstance.getSettings().data === newValue) {
                  settingFactory.renderHandsontable(scope.hotInstance);
                } else {
                  scope.hotInstance.loadData(newValue);
                  scope.htSettings.data = newValue;
                  **settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);**
                }
              } else if (newValue !== oldValue) {
                scope.htSettings[key] = newValue;
                settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
              }
            }, ['datarows', 'columns', 'rowHeights', 'colWidths', 'rowHeaders', 'colHeaders'].indexOf(key) >= 0);
          });
then you can fix the problem

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
