### ISSUE TITLE
Register a Custom Editor

### ISSUE THREAD

**Issue by stguitar** [handsontable/ngHandsontable#142]
I have a need to create a custom editor, and I am not sure i follow how to register that, when using this directive (wrapper) around basic handsontable. 

any documentation around this available?

**Comment by stguitar** [comment]
just so anyone else is curious, i figured out how to do this.

you can build the editor the same way as you would with or without nghandsontable, and simply add your editor javascript file to your index.html so that it is executed.

**Comment by estvmachine** [comment]
Can you share little code? :+1:

**Comment by stguitar** [comment]
No problem.

Create a JS file with something like

`(function(Handsontable){

var MyEditor = Handsontable.editors.DropdownEditor.prototype.extend();

MyEditor.prototype.open = function () {
    //impl an open method if needed
};

//Put editor in dedicated namespace
Handsontable.editors.MyEditor = MyEditor;

//Register alias
Handsontable.editors.registerEditor('myEditor', MyEditor);

})(Handsontable);`

Then in your index.html include a reference to that script file.

Then to use it in your directive, just use the `editor: myEditor` option.
