### ISSUE TITLE
Cell Format is not updating

### ISSUE THREAD

**Issue by crash21** [handsontable/ngHandsontable#143]
Hello,

I use cell attribute to pass cell format like:
`   {
   row:0,
   column:0
   className: "foo"
  } `

When i update this object with angular, it updates successfully in angular level but without changing cell format (does not apply cell format again to cells so classNames remain same).

Probably I need something to re-render or force update the table.
I got the hotInstance and used hotInstance.render() but again new cell format is not applied.

Any ideas?

Thanks a lot.

**Comment by crash21** [comment]
Hello

I found it, I have to use  hotInstance.init() and not  hotInstance.render() to update cells format.

**Comment by estvmachine** [comment]
Hi, you can share litte code, i think i got the same error.

**Comment by crash21** [comment]
OK so create the hot table and add an afterInit method:

     <div hot-table
                     hot-id="table-builder"
                     data-settings="{contextMenu: true, stretchH: 'all', afterInit: afterInit, }"
                     data-row-headers="true" data-min-spare-rows="grid.minSpareRows" data-datarows="grid.data"
                     data-columns="grid.columns" data-width="grid.getWidth" data-height="grid.getHeight"
                     data-cell="grid.cell">
    </div>


Now in angular side add this method:

    $scope.afterInit = function () {
           $scope.grid.instance = this;
    };

So now you have saved the instance of hot table in  $scope.grid.instance.

Now everytime you want to update table format just run:

    $scope.grid.instance.init();

**Comment by estvmachine** [comment]
Marvelous!

**Comment by estvmachine** [comment]
It seems the moment you create a handsonTable and the moment when you want to init is asyncronous, how you made for make this refresh just when start?. You can actually made works?, i can link the instance :+1:  but i cant use the method init without

**Comment by crash21** [comment]
How you mean? Can you post your code to check as well?
