### ISSUE TITLE
not updating settings

### ISSUE THREAD

**Issue by stguitar** [handsontable/ngHandsontable#144]
i have a ctrl.settings object that identifies the starting settings for the grid. 

later, by other user actions in the application, i need to update those and call handsontable updatesettings.  i can do this by directly referencing the handsontable instance, which works, but what i also need to do is at the same time modify the columns. 

Since there is a watch on the columns, i end up getting a call to updatesettings of handsontable 2 times. (one by me, and one due to the column manipulation).  This makes sense.

however, what doesnt make sense is that when the nghandsontable initiated update occurs due to the column manipulation, it doesnt re-parse my grid settings object, and basically undoes, or resets the settings back to the originally defined settings. 

what is the suggested way to handle this? right now ive got it working by just accepting the 2 calls to handsontable.updatesettings and as long as i manage the order, it basically works but it feels a odd to have to do it this way.

i have tried to simply change the settings in ctrl.settings as needed BEFORE updating the columns, thinking that the nghandsontable initiated update would see that but since it doesnt re-parse the settings object, and still passes the initially set/parsed settings to handsontable, my updates are ignored.

any suggestions?

**Comment by stguitar** [comment]
tangental to this, i need to specify the object to fillHandle so that I can prevent new rows and also prevent horizontal dragging. these object settings do not seem to work.

**Comment by mudassir0909** [comment]
@stguitar How do you get the access to hot instance?

**Comment by stguitar** [comment]
@mudassir0909 In most, if not all of the callbacks 'this' represents the hotInstance.  What I actually did was save a local variable in my controller as that, in the afterInit callback.

**Comment by mudassir0909** [comment]
Actually I figured it out after peeking into the source code & this is what I ended up doing https://github.com/handsontable/ngHandsontable/issues/96#issuecomment-228039718

Thanks for responding though :)

**Comment by AMBudnik** [comment]
Please track [the following issue list ](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Core%3A+update+settings%22)for updateSettings updates
