### ISSUE TITLE
ngHandsontable breaks persistent state

### ISSUE THREAD

**Issue by compwright** [handsontable/ngHandsontable#149]
If the `persistentState` option is enabled, state is saved in LocalStorage but not loaded on subsequent page loads.

This is because the element passed to Handsontable lacks an `id` attribute, so Handsontable generates a random ID to use on each page load.

**Comment by AMBudnik** [comment]
Hi @compwright 
I really appreciate your invetigation and effort to create a pull request.
Thanks! I will share this information with our developers.
