### ISSUE TITLE
issue with dynamic maxRows

### ISSUE THREAD

**Issue by kotmatpockuh** [handsontable/ngHandsontable#151]
For example in controller i have defined variable:

`$scope.maxRowsVal = 10;`

and after i'm loading this data from the server:

```
$http.get('/appi/info', {
  headers: {
    'Content-Type': 'application/json'
  }
})
.success(function (response) {
  $scope.maxRowsVal = response.Val;
});
```

but directive isn't changing (i can drag array - and new rows are creating)

`<hot-table settings="{colHeaders: colHeaders, maxRows: {{maxRowsVal}},...`

**Comment by Swatantramishra1** [comment]
Hi ,
this is my Handsontable where we declare only settings part not all . we can but from use perspective you have to define in controller ,will be better .

     <hot-table class="hot handsontable htRowHeaders htColumnHeaders" settings="settings"
                               row-headers="rowHeaders"  datarows="dba">
      <hot-column ng-repeat="column in Value" data="{{column.COL1}}" >
      </hot-column>
     </hot-table>

here are setting code which will resolve your issues.

>  $scope.settings = {
>             renderAllRows: true, stretchH: 'all', rowHeaders: true, manualrowresize: true, manualColumnResize: true, minRows: 1, colWidths: [250, 250, 250], cornerHeader: 200, maxRows:3
>         };

you can set dynamic **maxRows**
