### ISSUE TITLE
dropdown autocomplete options doesn't render

### ISSUE THREAD

**Issue by akoskm** [handsontable/ngHandsontable#152]
Following the documentation http://handsontable.github.io/ngHandsontable/ I expected this code to work, however, the list of possible option won't show up:

http://jsbin.com/geqiqucako/1/edit?html,js,output

**Comment by garypma** [comment]
I have the same issue, only I'm using an array of strings as the options. In my case the ngHandsontable.js throws and exception on line 33 (var row = this.instance.getSelected()[0];) The instance is null. I'm not sure if this is your issue or not, but they may be related. Either way, my dropdown doesn't render the options as well. Any help would be appreciated.

**Comment by hardik2792** [comment]
Facing similar issue, I have provide the data in required manner, it's not working..... do we have any other options.

https://github.com/handsontable/ngHandsontable/issues/165

**Comment by akoskm** [comment]
@hardik2792 I've corrected my fiddle http://jsbin.com/hegupugame/1/edit?html,js,output but I haven't found any solution yet.

I would close your issue, I think it is duplicate of this one.

**Comment by hardik2792** [comment]
@akoskm I have tried and concluded that if we add angular's directives like ng-repeat, ng-if, etc. it creates working issue.... So I have created JavaScript variable and appended the html part in it by looping on my data content... also I have followed the data structure as they followed:

Data structure:

[object Object] {
  address: "55884 USA",
  date: "3/23/1977",
  id: 1,
  isActive: "Yes",
  name: [object Object] {
    first: "Gwen",
    last: "Goodman"
  },
  price: 249.64,
  product: [object Object] {
    description: "Big Mac",
    options: [[object Object] {
  description: "Big Mac"
}, [object Object] {
  description: "Big Mac & Co"
}, [object Object] {
  description: "McRoyal"
}, [object Object] {
  description: "Hamburger"
}, [object Object] {
  description: "Cheeseburger"
}, [object Object] {
  description: "Double Cheeseburger"
}]
  }
}


However my requirement is not fulfilled... :(

**Comment by hardik2792** [comment]
Hello @akoskm,

I received this yesterday, Sharing this thinking it might help you.
http://jsbin.com/yabajixiyo/1/edit?html,js,console,output

Thanks.

**Comment by akoskm** [comment]
Hi @hardik2792, I see yours is working now.

What was the problem? The only difference I see is that i your data:

```
$scope.data = [['a', 'b', 'baz'], ['g', 'g', 'foo'], ['g', 'g', 'baz']];

**Comment by hardik2792** [comment]
Hi @akoskm , 
There is a change on HTML Side too. They have changed the syntax for dropdown. They have used 'type' attribute  to  represent it instead of autocomplete. If type is 'dropdown' then it shows the dropdown icon, and to load dropdown data the used 'source' attribute.

HTML Syntax:

<hot-column ng-repeat="column in segments" data="{{column.data}}" title="column.title" read-only="column.readOnly" type="column.type" source="column.source"></hot-column>

**Comment by akoskm** [comment]
@hardik2792 can you fix your comment, the HTML Syntax isn't visible. Thanks.

**Comment by hardik2792** [comment]
@akoskm 
Check the Link Below
http://awesomescreenshot.com/07c5z2vx6a

**Comment by akoskm** [comment]
Okay now it's visible in your comment too, you probably fixed it. :smiley:

**Comment by hardik2792** [comment]
Yes! I Did :smiley:

**Comment by ganeshkbhat** [comment]
Can I create a dropdown only for a cell? I have been trying to look for it but with no luck. I dont want entire column. Either entire row or single cell.

**Comment by AMBudnik** [comment]
Yes, you can. I have a vanilla demo but the logic is the same http://jsfiddle.net/handsoncode/wp7ynbng/1/
