### ISSUE TITLE
afterChange event doesn't provide correct row to match internal data when filtering.

### ISSUE THREAD

**Issue by garypma** [handsontable/ngHandsontable#153]
I have attached an afterChange event to my table. When the event fires after changing any cell the row provided in the charge argument is correct if I'm not filtering. While sorting I use the sortIndex to translate the sorted row to the correct data row. However, if I'm just filtering the table, there is no sortIndex and no other translation to map the row provided in the change param to the real row in my data. Here is my code:

$scope.itemChanged = function (change, source) {

```
        if (change === undefined || change === null)
            return;

        var row = change[0][0];
        if ($scope.participants !== undefined && $scope.participants.length > row) {
            var table = hotRegisterer.getInstance('compTable');
            var dataIndex = row;
            if (table.sortIndex.length > row) {
                dataIndex = table.sortIndex[row][0];
            }

            var part = $scope.participants[dataIndex];
            console.log("row = " + row + ", calculating bonus for " + part.fullName);
            compGridService.calculateBonus(part);
        }
    };
```

Under normal sorting or not sorting that row is mapped correctly, but when filtering the row returned is the row shown on the table not the ACTUAL row in my data. This is a major issue and may cause us to look for another solution if not resolved quickly. Maybe there is a translate feature, if so, any help would be great.

Thanks

**Comment by AMBudnik** [comment]
The issue relates to vanilla version. Please track changes to https://github.com/handsontable/handsontable/issues/4170
