### ISSUE TITLE
Columns disappearing

### ISSUE THREAD

**Issue by Wh1t3L0tus** [handsontable/ngHandsontable#154]
I have a table with a few columns :
![handsontable-bug](https://cloud.githubusercontent.com/assets/2016290/14705156/745d5310-07b8-11e6-986b-405e95cbb9c2.png)

When I scroll to the right I can see 4 of my columns are missing :
![handsontable-bug2](https://cloud.githubusercontent.com/assets/2016290/14705161/74716026-07b8-11e6-9053-3a742e233aa3.png)

Then I resize the 'Publication' column and the missing ones come back:
![handsontable-bug4](https://cloud.githubusercontent.com/assets/2016290/14705157/7464ad04-07b8-11e6-8090-7487bedf8c37.png)

When I come back to the left side my first and second column disappear:
![handsontable-bug5](https://cloud.githubusercontent.com/assets/2016290/14705158/74665f46-07b8-11e6-879a-dea7ad60dca5.png)

And by clicking on cells (here it's the one at row 11 and 'Titre' column ) and I can make them come back:
(Note: on the below screenshot I clicked on one cell but as a result four were selected)
![handsontable-bug6](https://cloud.githubusercontent.com/assets/2016290/14705160/746e5d7c-07b8-11e6-80ff-e2f534efa339.png)

![handsontable-bug7](https://cloud.githubusercontent.com/assets/2016290/14705162/747488d2-07b8-11e6-97cf-04deeb773c0b.png)

I can reproduce this from version 0.8.0 to 0.10.0.

**Comment by AMBudnik** [comment]
Hi @Wh1t3L0tus 
Does the same issue occurs in 0.24.2?
If so please create a demo where this issue is replicable - I'd be happy to take a look at it.

**Comment by Wh1t3L0tus** [comment]
Hmmm...I tried but without success. I'll re-open this issue later if I make it.
