### ISSUE TITLE
Destroy / Recreate table

### ISSUE THREAD

**Issue by crash21** [handsontable/ngHandsontable#155]
Hello,

What is the best way to destroy a table and then recreate it? I need it because after playing with its options like fixed headers/columns or show headers/columns it causing some UI bugs (like rows/columns are misplaced). So my idea is to destroy table and recreate it again but how?

Thanks.

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
