### ISSUE TITLE
Uncaught ReferenceError: Handsontable is not defined

### ISSUE THREAD

**Issue by lestersconyers** [handsontable/ngHandsontable#160]
I'm getting an reference error in ngHandsontable when it loads. Error is occurring very early at line `Handsontable.hooks.add("afterContextMenuShow", function() {...`

Here's what my code looks like. Any clues?

```
<link rel="stylesheet" media="screen" href="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.24.3/handsontable.full.min.css" />
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.24.3/handsontable.full.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ngHandsontable/0.10.0/ngHandsontable.min.js"></script>

<script>
    angular.module('theApp', ['ngHandsontable']);
</script>
```

**Comment by murph1329** [comment]
Add the event hook in settings

`  this.settings = {
    contextMenu: [
      'row_above', 'row_below', 'remove_row'
    ],
    // callbacks have 'on' prefix
    onAfterInit: function() {
      console.log('onAfterInit call');
    },
    onAfterCreateRow: function(index, amount) {
      console.log('onAfterCreateRow call => index:' + index + ', amount: ' + amount);
    },
    **afterContextMenuShow: function () {
      alert('hi wes');
    },**
    onAfterRemoveRow: function(index, amount) {
      console.log('onAfterRemoveRow call => index:' + index + ', amount: ' + amount);
    }
  };
}`

**Comment by bsouthga** [comment]
yeah it looks like `ngHandsontable` is pretty much broken as of `0.10.0`, I downgraded to `0.9.0` and it seems to at least import.

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.

**Comment by MehdiRaza1998** [comment]
Same issue still occurring. What's the solution? 
I am using 
"ng-handsontable": "^0.13.2",

**Comment by AMBudnik** [comment]
Hi @MehdiRaza1998 
we no longer work on this project as we moved to the Angular 2+ wrapper.
