### ISSUE TITLE
ngHandsontable - Cell edit causes ng-model issue

### ISSUE THREAD

**Issue by murph1329** [handsontable/ngHandsontable#161]
This is a duplicate issue of one posted on the handsontable forum.  I'm including it here as well to see if the community has a work around.

Original Posting:
https://forum.handsontable.com/t/nghandsontable-cell-edit-causes-ng-model-issue/379/1

Details:
Browser: IE11
AngularJS: v1.4.10
ngHandsontable: 0.12.0

I'm only able to duplicate the following issue using IE11, Chrome works fine.

JSBin Sample:
http://jsbin.com/mutotikuke/edit?html,js,output

Steps to reproduce:
Edit any cell in "ID" column (do not press enter or any table navigation key)
After edit immediately click on "filter" textbox
Type text into "filter" textbox

EXPECTED RESULT: {{ctrl.filter}} should correspond to item in "filter" textbox
DEFECT: model is not updated

This is a critical issue to us as it could lead to data loss.

Thanks,
Wes

**Comment by murph1329** [comment]
UPDATES:
https://forum.handsontable.com/t/nghandsontable-cell-edit-causes-ng-model-issue/379/1

**Comment by murph1329** [comment]
UPDATE:

I've added a comment to the following ticket over at the AngularJS github site.  Honestly I'm not really happy about the feedback I'm seeing.

I'm not sure if there is anything the handsontable team can do about this issue but I really want to see that everyone is made aware of it as I believe it has the potential to be catastrophic due to the ease of data loss.

If anyone has a work around for it, even if it is a hackish type of approach, please share it with the community so we can be made aware of it.

Thanks,
Wes

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
