### ISSUE TITLE
You can't set read-only on multiple check box columns

### ISSUE THREAD

**Issue by garypma** [handsontable/ngHandsontable#162]
If you setup a angular ngHandsontable and setup two different check box columns, you can't set one to read only and the other to not. They will both still allow edits. Both have to be set to read-only or it doesn't work. I need a fix for this asap. Just change you basic angular example to have the following code and you will see the error right off:

hot-column data="isActive" title="'Is active'" type="'checkbox'"  checked-template="'Yes'"
                unchecked-template="'No'"></hot-column>
hot-column data="isActive2" title="'Is active'" type="'checkbox'" read-only checked-template="'Yes'"
                unchecked-template="'No'"></hot-column>

I would appreciate some kind of response. I have left several bugs and never seem to get any kind of response, or if I do it's not helpful.

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
