### ISSUE TITLE
TypeError: Cannot set property 'datarows' of undefined

### ISSUE THREAD

**Issue by AlejandroME** [handsontable/ngHandsontable#167]
Hello,

I'm using ngHandsontable 0.9.0 (with handsontable 0.14.0) and AngularJS 1.2.28 and i'm having a lot of problems with a very simple table. This is my code:

```
<hot-table colHeaders="true" startRows="7" manualColumnResize="true" datarows="td">
  <hot-column data="COLUMN_1" title="'COLUMN 1'"></hot-column>
  <hot-column data="COLUMN_2" title="'COLUMN 2'"></hot-column>
  <hot-column data="COLUMN_3" title="'COLUMN 3'"></hot-column>
  <hot-column data="COLUMN_4" title="'COLUMN 4'"></hot-column>
  <hot-column data="COLUMN_5" title="'COLUMN 5'"></hot-column>
</hot-table>
```

And this is part of my controller:

```
$scope.td = [{
  'COLUMN_1': ''
}, {
  'COLUMN_2': ''
}, {
  'COLUMN_3': ''
}, {
  'COLUMN_4': ''
}, {
  'COLUMN_5': ''
}];
```

But i'm getting this error in Chrome:

> TypeError: Cannot set property 'datarows' of undefined

And 5 more errors:

> TypeError: Cannot set property 'data' of undefined
> TypeError: Cannot set property 'data' of undefined
> TypeError: Cannot set property 'data' of undefined
> TypeError: Cannot set property 'data' of undefined
> TypeError: Cannot set property 'data' of undefined

For every column. That code worked with ngHandsontable 0.5.2 until it stopped working. With the 0.9.0 and current 0.12.0 doesn't work.
I've checked every example, every possible missing reference between my controller and my view and this doesn't work. So, i looked at the code in the compile block in the hotTable directive:

```
compile: function(tElement, tAttrs) {
        var _this = this,
          bindingsKeys;

        this.scope = settingFactory.trimScopeDefinitionAccordingToAttrs(settingFactory.getTableScopeDefinition(), tAttrs);
        bindingsKeys = Object.keys(this.scope);

        angular.forEach(bindingsKeys, function(key) {
          var mode = _this.scope[key].charAt(0);

          _this.$$isolateBindings[key] = {
            attrName: _this.scope[key].length > 1 ? _this.scope[key].substr(1, _this.scope[key].length) : key,
            collection: key === 'datarows',
            mode: mode,
            optional: false
          };
        });
...
```
`_this.$$isolateBindings` is the problem, because is `undefined` but it's curious because in the ngColumn directive (in the compile `block` again) i found this:

```
compile: function(tElement, tAttrs) {
        var _this = this;

        this.scope = settingFactory.trimScopeDefinitionAccordingToAttrs(settingFactory.getColumnScopeDefinition(), tAttrs);
        //this.$$isolateBindings = {};

        angular.forEach(Object.keys(this.scope), function(key) {
          _this.$$isolateBindings[key] = {
            attrName: key,
            collection: false,
            mode: key === 'data' ? '@' : '=',
            optional: false
          };
        });
...
```
Why is `//this.$$isolateBindings = {};` commented? I uncommented that line, renamed `this` with `_this` and added the same edited line in the compile block of `hotTable` and it worked:

**In the hotTable directive (compile block):**
```
compile: function(tElement, tAttrs) {
        var _this = this,
          bindingsKeys;

        _this.$$isolateBindings = {};
        this.scope = settingFactory.trimScopeDefinitionAccordingToAttrs(settingFactory.getTableScopeDefinition(), tAttrs);
        bindingsKeys = Object.keys(this.scope);

        angular.forEach(bindingsKeys, function(key) {
          var mode = _this.scope[key].charAt(0);

          _this.$$isolateBindings[key] = {
            attrName: _this.scope[key].length > 1 ? _this.scope[key].substr(1, _this.scope[key].length) : key,
            collection: key === 'datarows',
            mode: mode,
            optional: false
          };
        });
...
```

**In the hotColumn directive (compile block):**

```
compile: function(tElement, tAttrs) {
        var _this = this;

        this.scope = settingFactory.trimScopeDefinitionAccordingToAttrs(settingFactory.getColumnScopeDefinition(), tAttrs);
        _this.$$isolateBindings = {};

        angular.forEach(Object.keys(this.scope), function(key) {
          _this.$$isolateBindings[key] = {
            attrName: key,
            collection: false,
            mode: key === 'data' ? '@' : '=',
            optional: false
          };
        });
...
```

Is this a problem or am i missing something? I asked in stackoverflow (http://stackoverflow.com/questions/37798221/cannot-set-property-datarows-of-undefined-in-nghandsontable) without any success and i hope that someone can give me advice about this.

**Note that in Firefox (last version) is happening the same.**

Thank you

**Comment by mathiasconradt** [comment]
Having the same problem!

**Comment by mathiasconradt** [comment]
I just found this:

https://github.com/handsontable/ngHandsontable/blob/develop/index.html#L69

> Note: ngHandsontable supports angular in version 1.3 and greater.

So I guess it's because of the older Angular version you are using (untested).

**Comment by AlejandroME** [comment]
@mathiasconradt Got it! I have to upgrade our Angular version. Meanwhile i think that i have to disable the library.
Thank you for your help.
