### ISSUE TITLE
"ReferenceError: Handsontable is not defined" when using AMD (RequireJS)

### ISSUE THREAD

**Issue by Technohacker** [handsontable/ngHandsontable#169]
Hey all,
I've had a problem running ngHandsontable with RequireJS.
Since Handsontable already offers support for AMD (and AFAIK I haven't found any way to enable both global and AMD HoT), the pure JS API works flawlessly.

However, add in ngHandsontable with a shim config like this:
`ngHandsontable : { deps : [ "angular", "handsontable" ]}`

It then throws "ReferenceError: Handsontable is not defined" at this line in ngHandsontable:
`Handsontable.hooks.add('afterContextMenuShow', function() {`

Even if i try shimming HoT (which, I have heard, is not recommended) like this:
`handsontable : {deps : [ "moment", "pikaday", "zeroclipboard" ], exports : "Handsontable"}`

It still gives the same error (my guess being HoT still uses the AMD API instead of globals).

Hope someone can help
Thanks! :)

**Comment by dehim** [comment]
hi,i sugguest you to make a single JS file like this:(@handsontable ver:0.25.1)
`define(["../lib/handsontable/handsontable.full",
    "css!../lib/handsontable/handsontable.full"],function(Handsontable){
    window.Handsontable=Handsontable;
    return Handsontable;
});`

and in your main.js,make like this:
` paths: {
         .......
        'handsontable': '../lib/handsontable/handsontable',
        'angular-handsontable': '../lib/handsontable/ngHandsontable',
    },
 shim: {
        .......
        'angular-handsontable':{
            deps: ['handsontable']
        }
    },`

finally,use like this,and it works
`define(['app','angular-handsontable'], function (app) {
.....
}`

**Comment by Technohacker** [comment]
@dehim thanks for the suggestion! I'll try and report back :)
