### ISSUE TITLE
Get code of handsontable to ng

### ISSUE THREAD

**Issue by CrackerakiUA** [handsontable/ngHandsontable#170]
I am trying to implement this example http://jsfiddle.net/hv8797gz/
Basically i am trying to add button with an action. If we have some which do that, point me please.
From the jsfiddle, what we need to pull is `Handsontable.hooks.add` functions. How do we do that?

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
