### ISSUE TITLE
Unable to change color of cell after change of value using afterChange

### ISSUE THREAD

**Issue by ganeshkbhat** [handsontable/ngHandsontable#173]
I am trying to change the style of a cell and am not able to render it or change it. 

I have tried using afterChange, afterRender, getRenderer methods to make this change but have not been able to do it. It just doesnot apply it. What is the right way to change the style of the cell from within afterChange function? What function to call with what arguements is also fine though a demo is welcome.

**Comment by AMBudnik** [comment]
Hi @ganeshkbhat 
Here's a little more advanced example but if should help: http://jsfiddle.net/b2q58ea1/
If you type `1` in the `0, 0` cell whole column becomes red and the value `1` is populated down the column as well.

**Comment by ganeshkbhat** [comment]
Thanks @AMBudnik  I am using ngHandsontable and unable to change styles using afterChange method.  I am not sure whether it is the issue of the instance I am getting or the method of setting style properties.  The style dont get set at all. I am calling this set methods within the afterChange functions. Any example using angularjs?

**Comment by ganeshkbhat** [comment]
@AMBudnik Is there a way. I have tried hotRegisterer.getInstance('my-view').setCellMeta(row, col, key, val) to change style value in the afterChange callback but it does not persist not rendered. Is there a different way to render it?

**Comment by AMBudnik** [comment]
Hi @ganeshkbhat 
sorry for a late response.
I'm not an Angular expert but thanks to @budnix we got a working example: http://jsbin.com/sisayehelo/1/edit?html,js,output

**Comment by ganeshkbhat** [comment]
Thanks the issue got resolved. I was able to use this in afterChange method and change the styles of each single or multiple cells correctly. Thank you @AMBudnik and @budnix for the demo code. I was not doing .render() after changing the styles.
