### ISSUE TITLE
Table not showing until change

### ISSUE THREAD

**Issue by bobwah** [handsontable/ngHandsontable#174]
Hi
I've just started using handsontable. I am getting resonably promising results however when the table initially loads it is only showing the first column then if I click on this column it refreshes to what I 
expect. Any ideas why it is doing this?

http://codepen.io/bobwah/pen/NAYWvE

I know if I remove height and width on the table declarion this goes away though seems like there is a deeper underlying problem.

Thanks
Rob

**Comment by JunedS** [comment]
Facing similar issue here. Table refreshes only after clicking on the column and when page loads only 1st column is visible.

**Comment by ganeshkbhat** [comment]
Please remove ng-cloak=""from your template and it should be resolved.
