### ISSUE TITLE
How to implement custom plugin with ngHandsontable

### ISSUE THREAD

**Issue by marc-antoinepelletier** [handsontable/ngHandsontable#175]
Hey I was trying to write a custom plugin to handle all my API stuff (save and load data) for handsontable. I tried to follow the brief guide [here](https://github.com/handsontable/handsontable-skeleton/tree/master/plugins/external) , instead I created a service that is like a c/c of the skeleton example.

I attached the onAfterChange hook as well, but it's not trigger.. I can see my plugin in Handsontable.plugins but the name is empty.

Is there anywhere a quick example of how we can implement custom plugin with angularjs ?

thanks

**Comment by bradstokes** [comment]
You have to initialise the setting on the global Handontable class before initialising the ngHandsontable directive. Put the line below before you update the settings. 

Handsontable.DefaultSettings.prototype.nameOfMyPluginHere = false;

There is a line in the ngHandsontable that _only_ allows settings that have be instantiated on the global object. It is frustrating I know.

**Comment by marc-antoinepelletier** [comment]
Thank you @bradstokes ! I would never guess that. My workaround was waiting for the instance of handsontable to be created and then do an updateSettings.
