### ISSUE TITLE
Cell Tooltip option?

### ISSUE THREAD

**Issue by ganeshkbhat** [handsontable/ngHandsontable#177]
I saw a header tooltip option available in Handsontable. Is there a Cell data tooltip option in handsontable? 

I am basically fixing a cell size to a width of x(40px). If the data is longer than the width of the cell it should show 'data longer than width' as `data lon...` and on hover on the cell the cell should show a simple plain anchor/image tool tip with the complete data. Is it possible or I will have to manipulate the directive of ngHandsontable. If so which section should I make the change so it is rendered. I saw some changes to directives were not getting assigned. I believe there are multiple renders for same cell from different places, is it?

**Comment by AMBudnik** [comment]
Sorry, but there is no option build-in for a cell tooltip.
What you can do is to pack a content inside a div and use the HTML `title` attribute
