### ISSUE TITLE
date-format not working in hot-column directive

### ISSUE THREAD

**Issue by mathiasconradt** [handsontable/ngHandsontable#178]
I try to format a date column as follows, both with the `settings` as well as the direct `date-format ` attribute. Neither works. The column `type` is set to `date` and the provided data is of type `date`.

```
    <hot-column data="createdAt" title="'Date'" type="'date'"
          settings="{dateFormat:'DD/MM/YYYY', type: 'date'}"
          date-format="'DD/MM/YYYY'"
          correct-format="true"
          allow-empty="true" read-only></hot-column>
```

The date column would just not format. Other kinds of formatting, such as `numeric` types in the Severity column using `format`-attribute are working.

![screen shot 2016-08-20 at 10 12 17](https://cloud.githubusercontent.com/assets/295122/17829959/5035f1fc-66bf-11e6-8b0f-4a408913f9e7.png)

Complete table code:

  <hot-table read-only datarows="events" class="table table-bordered table-striped" row-headers="false" manual-column-resize="true">

```
    <hot-column data="createdAt" title="'Date'" type="'date'"
          settings="{dateFormat:'DD/MM/YYYY', type: 'date'}"
          date-format="'DD/MM/YYYY'"
          correct-format="true"
          allow-empty="true" read-only></hot-column>

    <hot-column data="eventType" title="'Event Type'"></hot-column>
    <hot-column data="user.displayName" title="'User'"></hot-column>
    <hot-column data="ipAddress" title="'IP Address'"></hot-column>
    <hot-column data="severity" title="'Severity'" type="'numeric'" format="'$ 0,0.00'"></hot-column>
    <hot-column data="eventMessage" title="'Message'"></hot-column>
    <hot-column data="" title="'Old data'"></hot-column>
    <hot-column data="" title="'New data'"></hot-column>
  </hot-table>
```

Using ngHandsontable 0.12.0, Handsontable 0.26.1.

Unfortunately there is not a single demo available in the demo section using the `date-format` attribute with the Angular directive.

Originally posted on http://stackoverflow.com/questions/39052001/nghandsontable-date-format-not-working-in-hot-column-directive

**Comment by mathiasconradt** [comment]
Update: I just found that

On https://github.com/handsontable/ngHandsontable/ it says:

> All Handsontable options listed here should be supported. Options in camelCase mode should be passed to the directive in hyphenate mode e.q autoWrapCol: true -> ...

but it does not seem to be the case. Also the '`renderer`' option does not work.

I tried to apply a custom renderer or another standard renderer (i.e. checkbox) to one of my columns, but it has no effect.

**Comment by budnix** [comment]
Hi @mathiasconradt, unfortunately `date-format` doesn't work in the same manner than `format` (for numbers). This issue is related with Handsontable itself and you can track changes [here](https://github.com/handsontable/dev-handsontable/issues/134).

**Comment by budnix** [comment]
Workaround for this issue is call `validateCells` method after table initialization. It forces the correction date format to another. I've created demo [here](http://jsbin.com/nipagukali/1/edit?html,js,output).

**Comment by mathiasconradt** [comment]
Thanks for the info and workaround, @budnix . My workaround has been so far to just use a custom renderer and call the date formatting in there. But I guess your approach is more elegant.
Since there is already another open ticket for this, I will close this one.
