### ISSUE TITLE
Insertion of row not working after column sorting

### ISSUE THREAD

**Issue by abhishek-1985** [handsontable/ngHandsontable#181]
Hi,

Am new to angular and ngHandsonTable. So please pardon me if I have done anything silly.

Now, my particular scenario as follows :-
1. onAfterColumnSort event should recreate the nghandsontable data based on some business rules.
2. Once columns are sorted, we would want to right click and insert row in the table.

However, the insertion of row above or below does not work and the table becomes wacky with 2 blank rows

Attached is the js fiddle - [jsfiddle code](http://jsbin.com/tafojozizi/edit?html,js,output)

Could you help me identify the issue ?

Regards,
Abhishek

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.

ps. the demo does not longer work
