### ISSUE TITLE
handsontable does not show all columns untill click

### ISSUE THREAD

**Issue by shivajiwagh** [handsontable/ngHandsontable#184]
I am using tabs to show data and charts. On first tab I have chart and second tab data is displayed using angular controller. However, on when click on second that it does not render all columns and displays only first column. After anywhere on the table or on the scrollbar it shows all the columns. What is going wrong here? Do I need to implement anythings specific to render?
Please have a look at the following images.
Here is the chart on first tab:
![chart](https://cloud.githubusercontent.com/assets/16300506/18615470/a525cea4-7dc5-11e6-8b1e-1eb7dee07605.jpg)
And the data which does not render all columns:
![data](https://cloud.githubusercontent.com/assets/16300506/18615474/bbdb7f22-7dc5-11e6-923a-7cc7d563b58e.jpg)

**Comment by pistou** [comment]
I have the same issue.
It acutally **does not load any other column at all**, i.e. there is **only one `td`** in `instance.view`.

To me, it seems like there is a relation with tabs too.
I have no clue what it could be though.

**Comment by shivajiwagh** [comment]
Try using settimeout function of JavaScript and see if it works.

**Comment by motin** [comment]
Having the same issue, but not with ngHandsontable, just handsontable, so you might want to report this upstream since it does not seem to be specific to ngHandsontable.

**Comment by motin** [comment]
Found some clues as to how to solve this. Our project also uses angular, but not ngHandsontable, and the issue seemed to be Handsontable initializing while being hidden (https://github.com/handsontable/handsontable/issues/1418), so check your ng-if/ng-show tags.

**Comment by duhaime** [comment]
I had the same trouble when rendering a table inside a hidden modal. I resolved the problem by initializing the table after the modal became visible.

**Comment by dphansti** [comment]
I have this same issue.  My handsontable is in a tabpanel.  If the tabpanel is selected on launch then it looks fine.  If a different panel is selected by default then columns are missing.  How do you initialize the table only after it is visible (tab is selected)?

**Comment by AMBudnik** [comment]
Hi @dphansti have you tried to initialize the Handsontable instance as @duhaime proposed? Currently, it is the best way to make it visible.

**Comment by juan619** [comment]
setTimeout(function(){$scope.recargarTabla()},10);

  $scope.recargarTabla = function(){
        $scope.hot1.updateSettings({
//
        });
        $scope.hot1.render();
    };

**Comment by mahesh00400** [comment]
Use hot.render();hot.refreshDimensions();. This will solve the issue. Thanks
