### ISSUE TITLE
Can't use dateFormat

### ISSUE THREAD

**Issue by chaucv93** [handsontable/ngHandsontable#188]
I can't use dateFormat: 'MM/DD/YYYY' to format Date in Handsontable. 

I want Date is MM/DD/YYYY but it always DD/MM/YYYY. And when I click to this col -> it changes to red (error). 

Can anyone help me !! 

http://jsbin.com/dutasetula/edit?html,js,output

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.

ps. the demo doesn't work anymore
