### ISSUE TITLE
autocomplete fails when loading data from ajax source

### ISSUE THREAD

**Issue by itszerocode** [handsontable/ngHandsontable#189]
I am loading 'autocomplete' hot-column with `<hot-autocomplete datasource="Object" >`

In below code snippet from ngHandsontable.js

I am getting correct data in **column.optionList** but just  the parameter value **scope.datarows** is 'undefined'. Hence the dropdown column is actually not displaying  any data

Rest of the columns are correctly rendering the data.

`  if (scope.htSettings.columns) {
            for (var i = 0, length = scope.htSettings.columns.length; i < length; i++) {
              var column = scope.htSettings.columns[i];

```
          if (column.type !== 'autocomplete') {
            continue;
          }
          if (!column.optionList) {
            continue;
          }
          if (typeof column.optionList === 'string') {
            var optionList = {};
            var match = column.optionList.match(/^\s*([\s\S]+?)\s+in\s+([\s\S]+?)\s*$/);

            if (match) {
              optionList.property = match[1];
              optionList.object = match[2];
            } else {
              optionList.object = optionList;
            }
            column.optionList = optionList;
          }
          autoCompleteFactory.parseAutoComplete(column, scope.datarows, true);
        }
      }`
```

**Comment by rahulthakur319** [comment]
Wrap it up inside `ng-if` div
```
<div ng-if="isLoaded">
   <hot-autocomplete datasource="Object" >
</div>
```
