### ISSUE TITLE
Access to all HOT instances through hotRegisterer

### ISSUE THREAD

**Issue by jongunter** [handsontable/ngHandsontable#190]
Would it be possible to access the (currently not public) array of all HOT instances through the hotRegisterer service?

Here's a use case: a single-page app with which I'm working has a "loading" overlay screen. This causes all the HandsOnTables to be rendered poorly initially (since they are hidden on their first render). I'd like to be able to tell all the tables to re-render, in one place, without adding (duplicate) code on each table to watch for the `loadingOverlay.hidden` event.

**Comment by AMBudnik** [comment]
Hi @jongunter 
This subject was mentioned in one of StackOverflow topics, please take a minute to check it: http://stackoverflow.com/questions/33521667/how-do-i-reference-an-already-created-handson-table-to-alter-it

**Comment by jongunter** [comment]
Thanks for your response. That thread isn't quite what I'm looking for. I actually made this modification for the copy of HOT that I'm using. If you want me to make a PR for this, I can write some tests and make the request:
https://github.com/handsontable/ngHandsontable/compare/develop...jongunter:patch-1

**Comment by jongunter** [comment]
Thinking about it more, maybe the list of instances should be returned as an array instead of a key/value pair object.

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
