### ISSUE TITLE
Is there any way to highlight particular row dynamically?

### ISSUE THREAD

**Issue by prathviraj080** [handsontable/ngHandsontable#192]
In my use case, I'm sending all the rows of handsontable to backend for validation and incase if there's any error in response, I want to highlight that particular row and column(In another color). 

Is there any easy hack to achieve this?

**Comment by AMBudnik** [comment]
Hi @prathviraj080 

you can use the `selectCell` method. It's the same for vanilla na ng versions
Here are the docs: https://docs.handsontable.com/pro/1.12.0/Core.html#selectCell
