### ISSUE TITLE
Unable to render formats and types for numeric in ngHandsontable

### ISSUE THREAD

**Issue by ganeshkbhat** [handsontable/ngHandsontable#195]
I am trying to render a single column as a numeric and unable to do it. I am using this to no effect.

<hot-table data="myCtrl.items"> <hot-column data="percentPoints" type="'numeric'" format="'00.00 %'" on-after-init="ceCtrl.onAfterInit" width="ceCtrl.capShow.width/11" ></hot-column> <hot-column data="price" type="'numeric'" format="'00,000.00'" on-after-init="ceCtrl.onAfterInit" width="ceCtrl.capShow.width/11" ></hot-column> </hot-table>

#Demo
NA, not other issues. Its a simple implementation

#Your environment
Version: Recent downloaded from github
Browser Name and version: IE 11, Chrome latest, Firefox
Operating System: Win7, Windows latest

**Comment by ganeshkbhat** [comment]
Any support here?

**Comment by AMBudnik** [comment]
Hi @ganeshkbhat 
This option should work as expected. Here I made an example: http://jsbin.com/jamunebefe/1/edit?html,js,output

**Comment by sonicwong** [comment]
Please make sure using ".full" js file: 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.34.4/handsontable.full.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ngHandsontable/0.13.0/ngHandsontable.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/handsontable/0.34.4/handsontable.full.min.css">
```

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
