### ISSUE TITLE
Paste Creates new, invisible cells

### ISSUE THREAD

**Issue by sam-whale** [handsontable/ngHandsontable#198]
I have a ng-handsontable with 3 columns. If I paste data from excel with 4 columns, each row object will create a new key: '4'. Since this is not a defined column, it will not show up in the table.

Is there a way to disable this so that the object will save the 3 columns of data if 3 columns are defined?

My ng-handsontable: 
```    
    <hot-table settings='{{settings}}' col-headers='true' row-headers='true' height='300' datarows='data'>
        <hot-column ng-repeat='column in columns' data='{{ column.data }}' source='products'
    title='column.title' type='column.type' format='column.format' read-only='column.readOnly' width='column.width'>
        </hot-column>
    </hot-table>
```

**Comment by SgtWiggles** [comment]
My current patch is removing keys which are numeric.
