### ISSUE TITLE
Click outside table area with dropdown open causes error: 'Cannot read property '0' of undefined'

### ISSUE THREAD

**Issue by Ullidtz** [handsontable/ngHandsontable#199]
If I open a dropdown in the table and then click outside the table area I get the following error:
```
ngHandsontable.js:39 Uncaught TypeError: Cannot read property '0' of undefined
    at ColumnSettings.column.source (ngHandsontable.js:33)
    at ColumnSettings.Handsontable.AutocompleteValidator [as validator] (handsontable.js:22572)
    at handsontable.js:5323
```

It fails on this line: `var row = this.instance.getSelected()[0];` inside the `parseAutoComplete` method.

I tried inserting the following code before line 33:
```
          var selected = this.instance.getSelected();
          if(!selected || selected.length === 0){
            process("");
            return;
          }
```

(To reproduce the error you have to make sure nothing is highlighted in the dropdown, you may need to type into the field ensuring the value entered doesn't match any of the options.)

This fixes the issue on my end, but I'm not sure if it's the correct way to solve the issue though.

**Comment by aRealCat** [comment]
i have the  same problem

**Comment by Prahadeesh92** [comment]
We are experiencing the same issue with ngHandsontable.js of version 0.3.17 and handontable.full.min.js v0.13.1.  Is there any solution to fix this error?

**Comment by Ullidtz** [comment]
Currently your best options are to either just change the source code in your local copy (See the proposed fix in the question.)
Or you could make a fork from the version you are using, add the 5 lines of code shown in the question and submit it (Although I suspect it could take some time before it gets merged.)

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
