### ISSUE TITLE
Possible to trigger callback when clicking header of table?

### ISSUE THREAD

**Issue by naysayer** [handsontable/ngHandsontable#202]
Hello, 

I have looked through the documentation and I do not see anything indicating the functionality I am looking to obtain. Rather than doing a front end sorting, I an wanting to click a column header and have it trigger a callback so I can have my back end do the sorting of data for me. Is something like this possible? And if so how can I go about doing it?

**Comment by naysayer** [comment]
Hi, just want to bump this. Is there anyone with any information in regards to this?

**Comment by AMBudnik** [comment]
Hi @naysayer 

you can use `afterOnCellMouseDown` callback. Here are the docs: [afterOnCellMouseDown](https://docs.handsontable.com/pro/1.12.0/Hooks.html#event:afterOnCellMouseDown)
As mentioned

> For example clicking on the row header of cell (0, 0) results with afterOnCellMouseDown called
> with coords {row: 0, col: -1}.
