### ISSUE TITLE
Cells selected even though shouldnt be

### ISSUE THREAD

**Issue by jakubbares** [handsontable/ngHandsontable#203]
I have buttons related to selected cells in handsontable (eg. delete row). When I select a row then it remains selected even though I clicked elsewhere outside of the table. The problem is that the buttons remain active and operate with the previously selected row even though I want them to be inactive since I dont want the row to be selected.
Is it possible to check for clicking outside the table and resetting $scope.selected to undefined again?

**Comment by AMBudnik** [comment]
Hi @jakubbares 

We have an [`outsideClickDeselects`](https://docs.handsontable.com/pro/1.10.2/Options.html#outsideClickDeselects) option which is set to `true` by default. I guess you are already using it. You would need it if you want to work on selected cells and outside buttons.

**Comment by jakubbares** [comment]
The problem is that we work with variable $scope.selected that is filled with row data by using a hook 'afterSelection':

$scope.registerOnClick = function() {
						$scope.mTable = hotRegisterer
								.getInstance('users-table');
						$scope._selection = [];
						$scope.mTable
								.addHook(
										'afterSelection',
										function(r, c, r2, c2) {
											if (r != -1) {
												var row = tableService
														.translateSortedRow(
																$scope.mTable,
																r);
												$scope.selected = $scope.tablesettings.data[row];
												$scope._selection = [ r, c, r2,
														c2 ];
												$scope.$apply();
											}
										});
					}

Is there also a hook 'afterDeselection' or something similar?
The problem is how to fill $scope.selected with empty array or null exactly when we deselect.

**Comment by jakubbares** [comment]
Solved:

 $scope.registerOnDeselect = function() {
	            $scope.mTable = hotRegisterer
	                .getInstance('users-table');
	            $scope._selection = [];
	            $scope.mTable
	                .addHook(
	                    'afterDeselect',
	                    function(r, c, r2, c2) {
	                        $scope.selected = undefined;
	                        $scope._selection = [ r, c, r2,
	                            c2 ];
	                        $scope.$apply();
	                    });
	          }

**Comment by jakubbares** [comment]
There is a problem! 
I need to click on a button outside the table (to delete selected row) without deselecting. How can I do that?
Right now if click anywhere outside the table I deselect

**Comment by AMBudnik** [comment]
Hi @jakubbares 

if you do not want to use `outsideClickDeselects: false` and still using values from selection events you should push this piece of information outside and hold it as variables.

Here is an example: http://jsfiddle.net/handsoncode/2b70ve0h/

**Comment by jakubbares** [comment]
The example you gave in the fiddle is not an optimal solution because I never want to delete a row by clicking delete button without specifically choosing a row before.
In my original solution the issue is that the button is active when no row is chosen - it is in fact just a cosmetic problem. When I tried using the afterDeselect hook the buttons were inactive but it wasnt possible to press them because clicking outside the table meant deselecting. I need to solve this and this only. 
I would love to hear your suggestions how to solve this. 
Many thanks

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
