### ISSUE TITLE
Facing columns disappearing issue while scroll enabled 

### ISSUE THREAD

**Issue by ramesh586** [handsontable/ngHandsontable#204]
Hello,

Please help me out i'm facing following issue while have more columns than window . Please watch the video for reference
https://www.useloom.com/share/a4f4812e54d841a8bf2bd70cdd1e7999

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue and provide a working demo.
