### ISSUE TITLE
Change size of table on header setting

### ISSUE THREAD

**Issue by johnothetree** [handsontable/ngHandsontable#209]
I have an app where we have to dynamically change the headers depending on user input. Is there a way to change the number of columns/rows shown in the table to match the number of column/row headers on the fly? From what I'm seeing everywhere on the internet, the only way to do so would be to create a dummy data set to match the number of headers, but that's far from ideal if there's already data in the table. 

Currently doing: 

`var hotInstance = hotRegisterer.getInstance("dataEntry");
hotRegisterer.getInstance("dataEntry").updateSettings({
rowHeaders: mainRowHeaders
});`

but this doesn't expand the table if there are more headers than the number of current rows on the table

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
