### ISSUE TITLE
autocomplete Custom render

### ISSUE THREAD

**Issue by SISONKK** [handsontable/ngHandsontable#210]
I have an handson table implemented at my project. its columns are dynamic to load current week dates. now i need to write an autocomplete custom render for all the dynamic column. which must loads an array of data.and also im in need to set autocomplete selected by database value.

NB: The afterChange event should work on change autocomplete. how could i achieve that.

Tried like following,

```
 $scope.shiftRender = function (hotInstance, td, row, col, prop, value, cellProperties) {
                    var sel = document.createElement('select');
                    sel.name = 'drop1';
                    sel.id = 'Select1';

                    var cars = [
                      "volvo",
                      "saab",
                      "mercedes",
                      "audi"
                    ];

                    var options_str = "";

                    cars.forEach( function(car) {
                        options_str += '<option value="' + car + '">' + car + '</option>';
                    });

                    sel.innerHTML = options_str;
                    console.log(sel)
                    td.appendChild(sel);
                }


```

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
