### ISSUE TITLE
Row Headers changing header when header text contains dashes

### ISSUE THREAD

**Issue by johnothetree** [handsontable/ngHandsontable#211]
When setting my rowheaders for my table, it formats things weird when the text for the header contains dashes. 

Example: when setting the headers to `["1-5", "6-10"]`, i get the following table output:
![image](https://user-images.githubusercontent.com/23673013/28278683-7e887fc4-6ae3-11e7-9e8d-23ad3d06cba1.png)

I'm setting the headers by doing `hotRegisterer.getInstance("dataEntry").updateSettings({rowHeaders: rowHeaders});` and it only happens with rows, never columns. 

nghandsontable version: `"ngHandsontable":"v0.13.0"`
Chrome version: `Version 54.0.2840.99`

**Comment by AMBudnik** [comment]
Can you share a demo where the issue is replicable?
