### ISSUE TITLE
Current Active cell get hangs on switching the active cell it leads to one more tabs on hot-table

### ISSUE THREAD

**Issue by prachi9418** [handsontable/ngHandsontable#213]
In dynamic hot-table generation, cells for certain columns gets hanged over another column cells. After editing of the cell for a specific value. Active cell will not be able to switch on another cell on click of cursor to another cell. Another cell will also gets activated and will not be able to edit the content of the new cell.

**Comment by AMBudnik** [comment]
Can you share a demo that will help us to track the issue?
