### ISSUE TITLE
Safe to work with latest Handsontable (0.34.4)?

### ISSUE THREAD

**Issue by deenairn** [handsontable/ngHandsontable#219]
The latest verison of ngHandsontable has a dependency on the underlying Handsontable as of v 0.28.4. Is it safe to use ngHandsontable v 0.13.0 with the latest version of Handsontable (v 0.34.4), or are there any API changes which will break it? Is there any plan to release an update to this library in the future?

**Comment by pdemilly** [comment]
I started using it and so far found 1 problem. Handsontable.eventManager has been removed so this statement fails and the one later that set it to true. Since I am using a wrapper around this lib, I just set eventManager to {}

```
Handsontable.hooks.add('afterContextMenuShow', function() {
	  Handsontable.eventManager.isHotTableEnv = false;
});
```

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
