### ISSUE TITLE
Handsontable is not defined

### ISSUE THREAD

**Issue by bchoddny** [handsontable/ngHandsontable#220]
Hi, 
I'm trying to migrate from handsontable-pro 1.3.0 to the latest 1.14.2. I understood there are breaking changes, but experimenting the upgrade. The requirejs config that use to work fine with 1.3.0 doesn't work with the latest version. I keep getting "ReferenceError: Handsontable is not defined". Please advise, Thanks.

`require.config({
    paths: {
        'jquery': '../components/jquery/jquery',
        'bootstrap': '../components/bootstrap-javascript/bootstrap',
        'handsontable': '../components/handsontable-pro/dist/handsontable.full',
        // hot-pro dependencies
        'pikaday': '../components/pikaday/pikaday',
        'zeroclipboard': '../components/zeroclipboard/dist/ZeroClipboard',
        'moment': '../components/moment/moment',
        'hot-formula-parser': '../components/hot-formula-parser/dist/formula-parser',
        'numbro': '../components/numbro/dist/numbro'
    },

    shim: {
        'handsontable': {
            exports: 'Handsontable',
            deps: ['pikaday', 'zeroclipboard', 'moment', 'numbro', 'hot-formula-parser']
        },
        'cm-handsontable-pro': ['handsontable', 'select2', 'dompurify']
    }
});

`

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
