### ISSUE TITLE
Filter Row

### ISSUE THREAD

**Issue by JohanStrydom** [handsontable/ngHandsontable#222]
Is there a way of having a filter row with drop downs below the header?
![image](https://user-images.githubusercontent.com/9675956/32143369-f63a71e8-bcb0-11e7-9aa5-35bfbe23377d.png)

**Comment by AMBudnik** [comment]
Hi @JohanStrydom 

sure, you can. But you will get a normal drop-down cell type. Not the Filters UI.

**Comment by JohanStrydom** [comment]
Great stuff. Would you be able to please point me in the right direction to accomplish this?

**Comment by AMBudnik** [comment]
Hi,

here's http://jsfiddle.net/handsoncode/kyxupfhu/ an example but without the filter logic

**Comment by JohanStrydom** [comment]
That is 100%. Thanks a million!

**Comment by AMBudnik** [comment]
You're welcome @JohanStrydom
