### ISSUE TITLE
How to get the HOT instance?

### ISSUE THREAD

**Issue by Maximaximum** [handsontable/ngHandsontable#226]
I'm using the HOT directive like this:
```    <hot-table datarows="$ctrl.usersToImport" min-spare-rows="1">
      <hot-column data="Email" title="'E-mail'" validator="$ctrl.RequiredValidator"></hot-column>
      <hot-column data="LastName" title="'Family Name'" validator="$ctrl.RequiredValidator"></hot-column>
      <hot-column data="FirstName" title="'First Name'" validator="$ctrl.RequiredValidator"></hot-column>
      <hot-column data="Gender" title="'Male/Female'" type="'dropdown'" source="$ctrl.genderOptions"></hot-column>
      <hot-column data="JobTitle" title="'Job Title'"></hot-column>
      <hot-column data="Telephone" title="'Telephone'"></hot-column>
    </hot-table>
```

Now, in my controller I need to call `hotInstance.validateCells()` at a certain place in code. But how do I get the `hotInstance`?

I couldn't find any info on this in the docs.

**Comment by AMBudnik** [comment]
Hi @Maximaximum 

I have a demo that may help http://jsbin.com/digupecame/edit?html,js,output

**Comment by Maximaximum** [comment]
Thanks a lot!
Yet another question. I'd love to store the hotInstance as a property on my controller class, rather than calling `hotRegisterer.getInstance()` each time I need to get the instance. But if I try to get the instance in the controller constructor, or in the `$onInit` method (it's an angularjs component, not a general directive),  `getInstance()` returns `undefined` (obviously, it hasn't been constructed yet). Could you give me a hint on which controller lifecycle hook should I use to be able to reliably get the instance?

**Comment by AMBudnik** [comment]
Sorry for the delay. I have checked some possible approaches and ask our developer but currently this action i not available
