### ISSUE TITLE
Content is not displayed within merged cells

### ISSUE THREAD

**Issue by kuzniets** [handsontable/ngHandsontable#227]
**Description:** Content is removed from merged cells if merge cells from right to left (or from bottom to top) and start to type text immediately.

**Steps:**

1. Merge cells in a next way - e.g 1st selected cell is D4, last selected cell is D2
2. Type text immediately after merging
3. Press enter

**Actual Result:** Content does not display in the merged area, content is actually written in the first cell which was selected while merging and this content is not visible
**Expected result:** Content displays within merged area

**Comment by AMBudnik** [comment]
Hi @kuzniets 

As we do not have a demo can you record the behavior, please?

**Comment by kuzniets** [comment]
@AMBudnik Sure

https://vimeo.com/254845124

**Comment by AMBudnik** [comment]
I have also replicated the same issue using the vanilla version on our website demo

https://docs.handsontable.com/pro/1.15.1/demo-merged-cells.html
![gif](https://user-images.githubusercontent.com/10757813/35974140-2833f0e4-0cd8-11e8-9dc9-ea093fa16803.gif) 
that is why I am transferring the issue to our vanilla board at https://github.com/handsontable/handsontable/issues/4786

**Comment by kuzniets** [comment]
@AMBudnik Checked on Chrome Version 66.0.3359.139 (Official Build) (64-bit)
fixed :)

**Comment by AMBudnik** [comment]
@kuzniets thanks for checking :)
We can close this issue
