### ISSUE TITLE
the handsontable's cell editor feautre is it supposed to work with ngHandsontable ?

### ISSUE THREAD

**Issue by Bartaf83** [handsontable/ngHandsontable#229]
i'm trying creating a custom cell editor, i've tried this : 
`var SelectEditor = Handsontable.editors.BaseEditor.prototype.extend();`
as in the [cell editot tutorial page](https://docs.handsontable.com/0.35.1/tutorial-cell-editor.html)  but Handsontable.editors is always undefined.

**Comment by AMBudnik** [comment]
Hi @Bartaf83 

here's a method that access the editors http://jsbin.com/genutuwoka/edit?html,js,console,output
However it can be only done internally at the moment
