### ISSUE TITLE
accordion like table

### ISSUE THREAD

**Issue by sushant1221** [handsontable/ngHandsontable#230]
I am trying to achieve something like this as shown below.
Can anyone tell me the approach to solve this problem.

arrow is the button inside the cell on clicking that I need to expand and show the data within which has header on top i.e. 2016,2017... and so on?

![untitled](https://user-images.githubusercontent.com/8128497/36655864-40412b36-1aeb-11e8-9f80-a71cd274ea7b.jpg)

**Comment by sushant1221** [comment]
@AMBudnik  Can you tell me little about it. What approach should I take to implement this?

**Comment by AMBudnik** [comment]
Hi @sushant1221 

I have already answered the questions at https://github.com/handsontable/handsontable/issues/4839 where you made the same issue. I will close this ticket. Please continue any further conversation at https://github.com/handsontable/handsontable/issues/4839
