### ISSUE TITLE
Nested Rows 

### ISSUE THREAD

**Issue by sushant1221** [handsontable/ngHandsontable#231]
I tried implementing this [https://jsfiddle.net/handsoncode/gLsz2sLj/](url)
using ngHandsontable and  came up  with this [https://jsfiddle.net/vqkt0hgv/14/](url)

But in angular expand and collapse icons are not being shown?

Is there anything extra I need to add to get it working?

**Comment by AMBudnik** [comment]
Hi @sushant1221 

Please create issues with only on the one board. We just got the exact same issue at https://github.com/handsontable/handsontable/issues/4841

**Comment by sushant1221** [comment]
Got it . But could you please check for the issue? I have provided both the fiddles? Can  you help with that?

**Comment by AMBudnik** [comment]
Yes, I will. I just have https://github.com/handsontable/handsontable/issues/4841 opened. 

The ngHandsontable hasn't been updated for a long time as we now have Angular 5 we have moved our development on this wrapper that supports Angular 2+https://github.com/handsontable/angular-handsontable

I need to check if the nested rows are even able to work with the ngHandsontable and then reply you at https://github.com/handsontable/handsontable/issues/4841
