### ISSUE TITLE
issue when pasting html form into a cell. i cannot type in input fields

### ISSUE THREAD

**Issue by Raphael007123** [handsontable/ngHandsontable#236]
http://plnkr.co/edit/wFyBiwxRN9En0VdgHeMj?p=preview
issue when pasting html form into a cell. i cannot type in input fields.

**Comment by Raphael007123** [comment]
Hi @AMBudnik thanks for the reply.

Just paste basic form html, 

 <form action="/action_page.php" method="get">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <input type="submit" value="Submit">
</form> 

in a cell.  couldnot type in the input fields

**Comment by Raphael007123** [comment]
@AMBudnik sorry
` <form action="/action_page.php" method="get">
  First name: <input type="text" name="fname"><br>
  Last name: <input type="text" name="lname"><br>
  <input type="submit" value="Submit">
</form> `

**Comment by Raphael007123** [comment]
![screenshot 14](https://user-images.githubusercontent.com/38747000/39310220-7f07123e-4987-11e8-9e92-40974ae7ce31.png)
![screenshot 15](https://user-images.githubusercontent.com/38747000/39310222-7f64f0c0-4987-11e8-94fe-59ac7ca4b5d0.png)
![screenshot 16](https://user-images.githubusercontent.com/38747000/39310223-7fc9c1e4-4987-11e8-8e02-bde81a653141.png)

**Comment by AMBudnik** [comment]
Please add

```
beforeOnCellMouseDown: function(e){
			e.stopImmediatePropagation()
		}
```

and check if you still can't perform the action.

**Comment by Raphael007123** [comment]
@AMBudnik after pasting this code. I cant click on any cell

**Comment by Raphael007123** [comment]
@AMBudnik after pasting this code. I cant click on any cell

**Comment by AMBudnik** [comment]
It should be added to the cell that has the HTML inside. Currently, the cell selection steals the focus from the HTML's input.

**Comment by Raphael007123** [comment]
@AMBudnik did you mean adding hooks ??

**Comment by AMBudnik** [comment]
Each time that I want to access the plnkr demo I get `503` but let me create a Fiddle out of it.

**Comment by Raphael007123** [comment]
Its working for me 
Thanks @AMBudnik
