### ISSUE TITLE
manualRowMove feature not implemented in nghandsontable

### ISSUE THREAD

**Issue by jnjagtap** [handsontable/ngHandsontable#238]
in hot table i can implement only few feature .i want to implement manualRowMove,manualcolumnMove,resize row/column. how to implement this(community edition feature)?

**Comment by AMBudnik** [comment]
Hi @jnjagtap 

here http://jsbin.com/yohifaheyu/edit?html,js,output is an example for moving rows in the ngHandsontable

**Comment by jnjagtap** [comment]
hi @AMBudnik
