### ISSUE TITLE
manual resize in nghandsontable implementation

### ISSUE THREAD

**Issue by jnjagtap** [handsontable/ngHandsontable#239]
Hello,

I am using this config:
`<div hot-table
    stretch-h="'all'"
    settings="{contextMenu: ['row_above', 'row_below', 'remove_row'] }"
    rowHeaders="false"
     manual-row-resize:"auto",
     fixed-Columns-Left: "2"
    datarows="gridData">
</div>`

))
Unfortunately resize and fixing column is not working. Is there something wrong I am doing or is there a workaround to ,make it work?

>

**Comment by AMBudnik** [comment]
The code did not attach. Can you share a demo?

**Comment by jnjagtap** [comment]
``  <hot-table  
    context-menu="true"
    row-headers="true"
    col-headers="true"
    stretch-h="'all'"
    datarows="vm.tblData"
    min-spare-rows="1"
    manual-row-move scroll-v="auto"
    manual-column-move scroll-h: "auto",
    formula="true"
     manual-row-resize:"true"
    manualColumnResize: true,
    fixed-Columns-Left: "2"
    row-headers fixed-rows-top="2"
  ><hot-table>

**Comment by jnjagtap** [comment]
```` <hot-table
context-menu="true"
row-headers="true"
col-headers="true"
stretch-h="'all'"
datarows="vm.tblData"
min-spare-rows="1"
manual-row-move scroll-v="auto"
manual-column-move scroll-h: "auto",
formula="true"
manual-row-resize:"true"
manualColumnResize: true,
fixed-Columns-Left: "2"
row-headers fixed-rows-top="2"

**Comment by jnjagtap** [comment]
i am using nghandsontable directive

**Comment by jnjagtap** [comment]
i am not able to see demo can u please reshare it?

**Comment by AMBudnik** [comment]
Sure, here it is http://jsbin.com/gukokipusa/edit?html,js,output

**Comment by jnjagtap** [comment]
resize of row/column done but fixing row/column not working.scroll bar is added to output page not table.

**Comment by AMBudnik** [comment]
If the same code works in the JSBin and doesn't work in your app there should be something blocking it. Are you able to share any example where I'd be able to replicate the bug?

**Comment by jnjagtap** [comment]
thank u so much @AMBudnik  but i have resolved issue

**Comment by AMBudnik** [comment]
You're welcome. I'm happy that it has been solved. I guess that we can close the issue
