### ISSUE TITLE
can we make certain rows  data bold or can we render row

### ISSUE THREAD

**Issue by jnjagtap** [handsontable/ngHandsontable#244]
want to make certain rows from table bold.

**Comment by AMBudnik** [comment]
Hi @

you can use a [`cells` method](https://docs.handsontable.com/pro/5.0.0/Options.html#cells) to perform these operations. Are the bolding follows any pattern (recursion)?

**Comment by jnjagtap** [comment]
i just want to make row in bold style where row containing data  total 

![screenshot from 2018-07-19 11-17-28](https://user-images.githubusercontent.com/40597317/42923932-9755d9c4-8b45-11e8-9ed8-d7fa6ddea299.png)

**Comment by AMBudnik** [comment]
If you want to base the styling on data you can use the `getDataAtCell` method. Here's the code to use http://jsfiddle.net/mdfya5po/

**Comment by jnjagtap** [comment]
how do i add classname(styling) in nghandsontable

**Comment by jnjagtap** [comment]
so if i m not using pro then how can i can i implement this in nghandsontable

**Comment by AMBudnik** [comment]
The following option works also for Handsontable CE, only the demo uses PRO resources.

**Comment by jnjagtap** [comment]
i got instance but getDataAtCell  method gives mi null value all the time

**Comment by AMBudnik** [comment]
Can you create a demo (for example in the JSFiddle or CodePen) where this issue can be replicable?
