### ISSUE TITLE
Error: Cannot read property 'getSettings' of null

### ISSUE THREAD

**Issue by minalkumar2893** [handsontable/ngHandsontable#268]
After upgrading to ngHandsontable 0.13.2 and handsontable 8.0.0, when i enter data into the table i get this error in the console:
![image](https://user-images.githubusercontent.com/46880667/94554802-3e54ad80-0278-11eb-8fee-7fba9ec4c872.png)

**Comment by AMBudnik** [comment]
Hi @minalkumar2893 

Could you send me (support@handsontable.com) your demo/implementation?

**Comment by elquimeras** [comment]
> With the last update of library the hansontable lost scope when is used behind a ng-if, my solution was use a ng-show, maybe set a custom context to your grid api can solve the problem too if the first solution is not enought in your case.
> 
> Post your code to take a look around

From Issue #269 I think that can be the same problem

**Comment by AMBudnik** [comment]
We do not have any update for this topic, but I guess that you're right @elquimeras thank you for sharing. I will close this ticket.
