### ISSUE TITLE
startRows does not reflect because of binding to datarows

### ISSUE THREAD

**Issue by ktal90** [handsontable/ngHandsontable#27]
My ngHandsontable in my html is as such:

```
<div id="grid" ng-if="gridRows">
    <hot-table
        settings="{colHeaders: colHeaders, contextMenu: ['row_above', 'row_below', 'remove_row', 'undo', 'redo']}"
        rowHeaders="true"
        minSpareRows="1"
        startRows="5"
        datarows="gridRows">
       <hot-column data="frequency"    
            title="'Frequencies'"
        width="150">
       </hot-column>
        <hot-column data="level"
        title="'Levels"
        width="150">
       </hot-column>
    </hot-table>
</div>
```

Since `gridRows` is an empty array to start with, `startRows` has no effect. The expected behavior should be that if `gridRows` is empty, `startRows` is in effect and should display the desired 5 rows. If `gridRows` is not empty, then the implemented behavior should take precedent. Please enforce `startRows` if `datarows` is empty.

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
