### ISSUE TITLE
Documentation and Loading data

### ISSUE THREAD

**Issue by maxstudener** [handsontable/ngHandsontable#28]
Documentation doesn't say you need to put ngHandsontable in the angular.module block. Also when i change datarows binding in the controller nothing works anymore because you cant load data via angular http in controller in the datarows binding variable, the scope.$parent.watch only check the scope of the table not the controller https://handsontable.com/demo/ajax.html

**Comment by kubak10** [comment]
Please check out version 0.5.1
Data loading and map notation is supported.
Thank you for your commitment.
