### ISSUE TITLE
minSpareCols and minCols options do not appear to be supported

### ISSUE THREAD

**Issue by sarahquigley** [handsontable/ngHandsontable#36]
Hi,
Thanks for all your good work on ngHandsontable.  I just started using experimenting with this library recently. You say you support all handsOnTable options. In the handsOnTable wiki, it describes 2 options as being available: minSpareCols and minCols.

When I attempt to set either of these (minSpareCols or minCols) on the hot-table directive, the settings have no effect (no extra columns are rendered above and beyond those in my datarows). I have not had similar issues using minSpareRows or minRows - these settings work as expected.

I've tried setting these both as part of the settings object and as an attribute on its own:
```
<hot-table settings="{minSpareCols: 20}" datarows="myDataRows" colHeaders="myColHeaders" columns="myColumns"></hot-table>
```
```
<hot-table minSpareCols="20" datarows="myDataRows" colHeaders="myColHeaders" columns="myColumns"></hot-table>
```
```
<hot-table settings="{minCols: 20}" datarows="myDataRows" colHeaders="myColHeaders" columns="myColumns"></hot-table>
```
```
<hot-table minCols="20" datarows="myDataRows" colHeaders="myColHeaders" columns="myColumns"></hot-table>
```
None of these approaches have worked. Would it be possible for support to be added for these options?

Many thanks.

**Comment by kubak10** [comment]
@sarahquigley 
We are working on this.

**Comment by AMBudnik** [comment]
Hi [here's](http://jsbin.com/gucodemoco/edit?html,js,output)  the updated example. Now you can add `minSpareRows` and `minSpareCols` by adding:

```javascript
this.settings = {
    minSpareCols: 1,
    minSpareRows: 1
  };
```
