### ISSUE TITLE
"Insert column" feature in context menu greyed out

### ISSUE THREAD

**Issue by facadev** [handsontable/ngHandsontable#37]
I'd like to implement a completely free-to-edit table just as Excel. So I set the "datarows" attribute and enable context menu by setting it to be true, but I find it not allow me to add a new column because the menu item is disabled. If I remove the "datarows" attribute, then I am able to insert a column, which, however, makes no sense to me because there is nothing bound to the table.

Is it a restriction of ngHandsontable or am I doing anything wrong?

**Comment by facadev** [comment]
OK finally I figured it out by chance. If you want to insert columns, the datasource has to be an array, period.

**Comment by Sajid8** [comment]
Can I know how to insert what changes have to be made to do so
