### ISSUE TITLE
Not able to render handsontable

### ISSUE THREAD

**Issue by surabhi-batra** [handsontable/ngHandsontable#39]
I'm using the ngHandsOnTable, and downloaded the new version without the jQuery dependency. 

I included the following files  (latest version )handsontable.full.js, ngHandsontable.js and handsontable.full.css in my project along with angular.js (v1.3.3) and jquery-2.0.3. 

I used the example template given in the readme to load a sample hands on table, but I'm unable to see any table. Neither can I  find any errors or issues in the console? 

Could someone update the documentation in order to provide more clarity as to how to load a sample nghandsontable? 

Would be much appreciated!

**Comment by kubak10** [comment]
Hello.
JQuery is no needed any more.
Please check out newest version - it's online now.
