### ISSUE TITLE
Header  shadow disappear when put the grid in  ui-bootstrap tab.

### ISSUE THREAD

**Issue by majj** [handsontable/ngHandsontable#41]
![handsontable1](https://cloud.githubusercontent.com/assets/543810/5545468/4340cabe-8b5e-11e4-89ce-41aaa6c4e242.png)
![handsontable2](https://cloud.githubusercontent.com/assets/543810/5545469/4344d94c-8b5e-11e4-83ad-faf38753b2d6.png)

when click the grid,it show the shadow.

**Comment by AMBudnik** [comment]
The behavior has changed as currently there is no header shadow
