### ISSUE TITLE
MergeCells is not working

### ISSUE THREAD

**Issue by HandsTest** [handsontable/ngHandsontable#47]
Hi,

mergeCells ="true" settings has no effect in context menu.
mergeCells: [{row: 1, col: 1, rowspan: 3, colspan: 3}]  does not merge cells.

http://jsfiddle.net/veyx8Lz1/2/

**Comment by D2Phoenix** [comment]
It's may be fixed by adding "mergeCells" property to Handsontable.DefaultSettings

**Comment by rasekar2000** [comment]
<hot-table
							settings="{colHeaders: colHeaders, contextMenu: ['row_above', 'row_below', 'remove_row'], afterChange: afterChange , mergeCells: [{row: 1, col: 1, rowspan: 1, colspan: 3},{row: 4, col: 1, rowspan: 3, colspan: 3}  ] }"
							rowHeaders="false"
							minSpareRows="minSpareRows"
							datarows="db.items"
							height="300"
							width="700"> This one is not working . Hi @D2Phoenix  , can you please confirm will this work? Basically looking forward given below URL to reproduce this example in ngHandsonTable..  Please let me know. Thanks in advance. 

http://handsontable.com/demo/merge_cells.html

**Comment by D2Phoenix** [comment]
Hi, @rasekar2000.
You must modify core.js file. Simply add mergeCells property to [DefaultSettings.prototype](https://github.com/handsontable/handsontable/blob/master/src/core.js)

**Comment by rasekar2000** [comment]
Hi @D2Phoenix  , Thanks for the note. My question is on ngHandsontable not on Handsontable, as  Handsontable this mergeCells is working fine.. Anyway, I am looking at the code of dist/handsontable.js --> https://github.com/handsontable/ngHandsontable/blob/master/dist/ngHandsontable.js 

This one has htSettings.. I believe, I can try setting this up !!!

/***
				 * Append handsontable container div and initialize handsontable instance inside element
				 * @param element
				 * @param htSettings
				 */
				initializeHandsontable: function (element, htSettings) {


Thanks and Regards,
Raj

**Comment by rasekar2000** [comment]
Hi @D2Phoenix ,

 as I see the following in the debug option, My guess is that mergeCells.js related isn't part of this ngHandsonTable but part of the original HandsonTable related JS files. So, in this ngHandsonTable this particular merge related section needs to be brought into this repository by @kubak10, please let him confirm, please.

Here are the sample debug message screenshots.. 

http://i61.tinypic.com/2qk7y1u.jpg
 htsettings of ngHandsonTable

http://i59.tinypic.com/2uz78sy.png
 userSettings in HandsonTable

http://i60.tinypic.com/zin7e9.png
 updateSettings in ngHandsonTable as well, is not showing the merged cell content.. 

Thanks and Regards,
Raj

**Comment by hermanwhyd** [comment]
This solution working for me: https://github.com/handsontable/handsontable/issues/1788
$scope.hot.mergeCells = [
	  {row: 1, col: 0, rowspan: 1, colspan: 34},
	  {row: 3, col: 0, rowspan: 1, colspan: 2}
];

// reload setting, render, & data
$scope.hot.instance.mergeCells = new Handsontable.MergeCells($scope.hot.mergeCells);
$scope.hot.instance.updateSettings({ mergeCells: $scope.hot.mergeCells, cells: $scope.hot.cells });
$scope.hot.instance.render();

**Comment by rasekar2000** [comment]
Hi @hermanwhyd , thanks for the update.. Will check this in couple of days and get back to you.
Regards,
Raj

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity.
