### ISSUE TITLE
Need Example in how to load datarows via Restservice

### ISSUE THREAD

**Issue by twindad2009** [handsontable/ngHandsontable#48]
Could anyone provide a more advanced example not just using static data for the table as using data Form a rest service allways returns an empty table. Don't know how the correct binding can be setup

**Comment by ramzy27** [comment]
same issue here

**Comment by ryantehbaker** [comment]
i'm not sure yet what is *causing* the issue, but here is my workaround:

the fix from https://github.com/Rouby/ngHandsontable/commit/6cf33ab25ec3ac370f68ef47714ea9d3f797cf4e solved part of the issue.

For whatever reason, i have to push the data into the array instead of just setting it to the results

```
        $scope.refreshData = function() {
            // datarows attribute is set to $scope.records
            $scope.records = [];
            $http.get('/api/things/dbtest').success(function(results) {
                $scope.hotvisible = true;
                // for some reason it works when i push it into the array 
                // instead of just $scope.records = results
                results.forEach(function(result) {
                    $scope.records.push(result);
                });
            });
        };
```

**Comment by rasekar2000** [comment]
Hi @ryantehbaker 

<hot-table
    settings="{colHeaders: colHeaders, contextMenu: true, mergeCells:true, afterChange: afterChange, afterInit:afterInit,mergeCells:mergeCells}"
    rowHeaders="false"
    minSpareRows="minSpareRows"
    datarows="db.items"
    height="300"
    width="700">
    <hot-column data="id" title="'ID'"></hot-column>
</hot-table>

As of now populating the data in the afterInit method. But mergeCells is preceding the activity and Forces to give all the mergeCells ahead of the time..
   Can you please suggest where do we call your $scope.refreshData method in such scenario?
   Thanks in advance. 

Regards,
Raj

**Comment by rasekar2000** [comment]
Hello Team,

 < hot-table
        settings="{data: data,colHeaders: colHeaders, contextMenu: true, mergeCells:true ,afterChange: afterChange, afterInit:afterInit ,  mergeCells:mergeMyCells }"
        rowHeaders="false"
        minSpareRows="minSpareRows"
        datarows="db.items"
        height="500"
        width="700" >

 At this time, the data is fetch from DB directly, which allows Async call to NoSQL and works fine.. Yet the mergeCells expects the data to be feed first.  Its not accepting afterInit feed as well. So, can you please suggest best way to dynamically bring the merge cell data as well from DB.

Thanks and Regards,
raj

**Comment by motin** [comment]
I found this row to be the culprit: https://github.com/handsontable/ngHandsontable/blob/175d143f6fc8f963b22719abc90d8eadd43e9384/src/directives/ngHandsontable.js#L110

It basically prevents update of datarows unless the previous amount of datarows are the same as "minSpareRows" and the new amount of datarows are not. 

It has to be a bug, that line of code makes no sense at all. Comment it out and try it it works.

**Comment by rasekar2000** [comment]
Hi @motin , I haven't changed the size of the Data .. I mean both ROWS and Columns are fixed for my case. Yet, will review this for mergeCell Data retrieval from DB perspective. 

Regards,
Raj

**Comment by rasekar2000** [comment]
Hi Motin,

just put few console log to see when this $watch gets triggered. 
scope.$watch('datarows', function (newValue, oldValue) {
						if (oldValue) {console.log('watch .. oldValue', oldValue);}
						console.log("watch ..scope.htSettings.minSpareRows " , scope.htSettings.minSpareRows);
						if (oldValue.length == scope.htSettings.minSpareRows && newValue.length != scope.htSettings.minSpareRows) {
							scope.htSettings['data'] = scope.datarows;
							settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
						}
					});	

 Please see this Watch gets triggered only once.. Its not taking mergeCellsValue change consideration ..

http://i59.tinypic.com/2nsw1w1.jpg


Thanks and Regards,
Raj

**Comment by motin** [comment]
@rasekar2000 Comment out https://github.com/handsontable/ngHandsontable/blob/175d143f6fc8f963b22719abc90d8eadd43e9384/src/directives/ngHandsontable.js#L110 and https://github.com/handsontable/ngHandsontable/blob/175d143f6fc8f963b22719abc90d8eadd43e9384/src/directives/ngHandsontable.js#L113 - does it work then?

**Comment by rasekar2000** [comment]
Hi @Motin, Before commenting out, i wanted to check, how many times, the $scope.watch is getting called for..
 in ht-settings, 
  data: data  is fetching the data asynchronously ..Even before that mergeCells , values are retrieved synchronously... 
 So,  $watch is not getting called after the initial data change.. See, the screenshot @ http://i57.tinypic.com/2lo6stl.jpg 
 By the way , I am using next version https://github.com/handsontable/ngHandsontable/blob/master/dist/ngHandsontable.js
 And hence you will see the line number around 265..

Regards,
Raj

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
