### ISSUE TITLE
Click the button to how the data assignment datarows

### ISSUE THREAD

**Issue by 331417100** [handsontable/ngHandsontable#49]
In angular，Usd Button assignment data to datarows，View not changing doesn't work

code
function ($scope) {
$scope.db = {};
$scope.db.items = [];

$scope.button=button;

function button()
      {
       var products = [ {"description": "Big Mac"   },  {"description": "Bic"   }];
      $scope.db.items = products ;
}

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
