### ISSUE TITLE
Can i user ng-repeat inside hot  hot-column

### ISSUE THREAD

**Issue by vibeesnan** [handsontable/ngHandsontable#50]
I need to use dropdown inside hot-column to populate the array of values.
Please help in this case.

**Comment by hardik2792** [comment]
@vibeesnan as I have working on ngHandsontable since few days... I found that the using ng-repeat may create issue... you need to populate those values in your controller itself and use it...

**Comment by pepijnolivier** [comment]
I can confirm it works, but performance drops majorly. I need to be able to use this on huge tables. Today I'm comparing performance between ngHandsontable and just using the 'raw' handsontable package

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.
