### ISSUE TITLE
bower.json for tag 0.5.1 has outdated version and angular dependency

### ISSUE THREAD

**Issue by ollietreend** [handsontable/ngHandsontable#51]
Hi,

It looks like the [bower.json definition tagged as 0.5.1](https://github.com/handsontable/ngHandsontable/blob/c85d98d7e82dd64ad1cea6c358d4b2ce26306181/bower.json#L3) is actually reporting as version 0.5.0. I notice that the [version in master](https://github.com/handsontable/ngHandsontable/blob/aa2eed7ade218d9b10d72cfa0c0e2f151db490db/bower.json#L3) has been updated since to 0.5.1 and to include the latest version of angular.

I'm currently having dependency problems as 0.5.1 is trying to pull in a version of angular 1.2 rather than 1.3.

Could we get a v0.5.2 tagged which clears up these issues? For now I'm having to override the handsontable dependency with my own.

My bower config:

```javascript
{
  "dependencies": {
    "angular": "1.3.*",
	"angular-ui-handsontable": "0.5.*"
  }
}
```

Output from bower:

```
Unable to find a suitable version for angular, please choose one:
    1) angular#~1.2.25 which resolved to 1.2.28 and is required by angular-ui-handsontable#0.5.1 
    2) angular#1.3.* which resolved to 1.3.13 and is required by app

Prefix the choice with ! to persist it to bower.json
```

Thanks

**Comment by ollietreend** [comment]
@kubak10 Is there any chance we can get a new tag with the correct version of bower.json please?

**Comment by ollietreend** [comment]
@warpech @kubak10 Any chance of a response on this? I'm growing concerned that this project is dead..

**Comment by zbjornson** [comment]
Would indeed be nice to know if this project will receive updates (e.g. support for HOT 0.15.0).

**Comment by budnix** [comment]
0.6.0 version which was released now has all dependencies up-to-date (angular ~1.4, Handsontable ~0.16).
