### ISSUE TITLE
Width configuration option has no effect on table width.

### ISSUE THREAD

**Issue by gscoppino** [handsontable/ngHandsontable#53]
http://jsfiddle.net/gscoppino/Lgj51s9h/

Play around with the width attribute of `hot-table`.

Expected result: Handsontable width occupies specified space.

Actual Result: Handsontable width remains the same as it would have been without the `width` attribute.

This does not happen with Handsontable standalone, see:
http://jsfiddle.net/gscoppino/ob98xmqu/

**Comment by Kroitoru** [comment]
Hey, I'm also having trouble the same issue.
I tried to make a watch(inside the hot-table directive) to width's attribute like this:
```javascript
scope.$watch('width', function (newValue, oldValue) {
		                scope.htSettings['width'] = newValue;
		                settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
		            }, true);```
But it's not helpfull.

**Comment by trognus** [comment]
Have you tried specifying a height? I've noticed a few instances where one property doesn't work without another, e.g. width doesn't work without height and minRows doesn't work without minSpareRows (and minSpareRows seems to need to be >= minRows)

**Comment by yinyihui** [comment]
These attributes should be seperated in my opinoin, can this be fixed?or has any other solutions?

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time and the provided demo does not load the table
