### ISSUE TITLE
$scope.columns in Ctrl is somehow being passed/inherited into hot-table directive

### ISSUE THREAD

**Issue by ryantehbaker** [handsontable/ngHandsontable#55]
look at the example:

http://jsfiddle.net/ab69qofc/2/

`$scope.columns` is **not** being passed into the directive, but it is somehow determining the columns that hot uses.

**Comment by ryantehbaker** [comment]
looks like the same issue is occurring but for `$scope.data`, which in this example, is not being passed into the directive, but is still populating the data in the hot:

http://jsfiddle.net/ab69qofc/4/

**Comment by chambery** [comment]
I think I have the same issue you're describing (and may have solved), but I couldn't get the jsFiddle to work:

http://stackoverflow.com/questions/33188138/nghandsontable-datarow-undefined-after-asynchronous-service-call/33193932#33193932

I had to set two $scope vars to make it work:
    $scope.transactions = [];
    $scope.minSpareRows = 0;

and in the partial:

     <hot-table min-spare-rows="minSpareRows" datarows="transactions">

**Comment by ryantehbaker** [comment]
Seems to be fixed now when looking at my previous jsfiddle
