### ISSUE TITLE
dropdown and autocomplete don't recognize option list

### ISSUE THREAD

**Issue by bnns** [handsontable/ngHandsontable#56]
Maybe I'm missing something but the following doesn't work:

``` html
<hot-table rowHeaders="true"
        colHeaders="ctrl.colHeaders"
        minSpareRows="1"
        stretchH="all"
        datarows="ctrl.data"
        height="600"
        width="1500">
    <hot-column data="field" title="'Field'" type="'autocomplete'">
        <hot-autocomplete datarows="option in ctrl.options"></hot-autocomplete>
    </hot-column>
</hot-table>
```

I believe the error has to do with line 127 inside parseAutoComplete:

``` javascript
if (options.object) {
  if (angular.isArray(options.object)) {
    source = options.object;
  } else {
...
  }
}
```

options.object is a string converted from the hot-autocomplete directive. But it needs to be an array of objects? In the above example, right now

``` javascript
options.object = 'ctrl.options'
```

but it needs to be 

``` javascript
options.object = [ 'option1', 'option2' ]
```

**Comment by bnns** [comment]
And another thing... here is the else block (when options.object is a string):

```javascript
...
  else {
    var objKeys = options.object.split('.')
    paramObject = data;

    while (objKeys.length > 0) {
      var key = objKeys.shift();
      paramObject =  paramObject[key];
    }
   ...
  }
...
}
```

This block is executed whenever user clicks a dropdown cell. paramObject is always empty, so paramObject[key] gives an error. This is using the same DOM as previous example.

**Comment by zszsoldos** [comment]
Same problem.

I wanted to use a different array from the $scope for options but I could not do this.

**Comment by steveed** [comment]
I am running into the same issue. Also the subsequent rows do not seem to copy the options over. If you go to the demo page and try the auto complete for Favorite Food on a new row you will see what I mean.

**Comment by ewu1209** [comment]
:+1:

**Comment by steveed** [comment]
Okay I figured out how do do the autocomplete values in the template. Just put some inline values in the datarow like below:

    <hot-autocomplete datarows="Value1, Value2, Value3"></hot-autocomplete>

**Comment by zszsoldos** [comment]
:+1:
How can I retrieve this list from the scope?

**Comment by steveed** [comment]
You could do something like the following.

In your controller:

    $scope.values = "Value1, Value2, Value3";

Then in the template:

    <hot-autocomplete datarows="{{ values }}"></hot-autocomplete>

**Comment by bnns** [comment]
I created a pull request https://github.com/handsontable/ngHandsontable/pull/62 to allow it to read the ng-repeat notation, i.e. field in $scope.options as well as to take the original string literal notation.

**Comment by bnns** [comment]
Another thing you have to do is to push the rows of your data one at a time, according to https://github.com/handsontable/ngHandsontable/issues/48

**Comment by steveed** [comment]
I am not having that issue now that I have the datarow stuff sorted for the autocompletes. I render multiple table instances on the page with multiple rows and they are rendering fine.

**Comment by AmmarBashir** [comment]
Can you please fiddle out for autocomplete as this is not working for me when inserting new row , it is not showing values in dropdown except the first row

**Comment by AMBudnik** [comment]
I think that we can close this issue as it hasn't been updated for a long time.

**Comment by AmmarBashir** [comment]
Yes correct
