### ISSUE TITLE
support for "validator"

### ISSUE THREAD

**Issue by richtier** [handsontable/ngHandsontable#57]
Handsometable supports [`validator` property](https://github.com/handsontable/handsontable/wiki/Options).

I don't think ngHandsometable does, or at least I cannot get validator to work by doing:

```html
        <hot-column
          data="username"
          title="'Username'"
          validator="validate">
        </hot-column>
```

where `validate` is a function on the scope of the model.

Should `validator` work?

**Comment by richtier** [comment]
@warpech @kubak10 @jansiegel  Any chance my [PR that fixes this](https://github.com/handsontable/ngHandsontable/pull/59) can be merged?

It's been open for almost 2 months :)

**Comment by budnix** [comment]
Added in 0.17.0-beta1
