### ISSUE TITLE
Can't get hold of the HotTable instance

### ISSUE THREAD

**Issue by thisispaul** [handsontable/ngHandsontable#63]
Since https://github.com/handsontable/ngHandsontable/commit/7962acb2317212270fb15f8259f200ded80b35a2 when you removed the jQuery depenedency, there doesn't seem to be a way for me to get hold of the handsontable instance so I can callmethods (render(), destroy() etc) on it.

Before I was just getting the instance via `container.data('handsontable')` but now that jQuery is not being used this no longer exists.

I agree it is best not to use jquery inside this directive, I just wonder if there is a way to allow us to call methods on the instance in our controllers?

**Comment by HandsTest** [comment]
Try the option given in 

https://github.com/handsontable/ngHandsontable/issues/34

**Comment by thisispaul** [comment]
Hmm, Yes that does get me the instance.

it is causing me aproblem though. Currently when the user navigates away from the page with the table on i call the destroy() function on the table (if i dont then handsontable still seems to be firing its events when scrolling the page etc)

The issue is when I do that, and then go back to the page the init function isnt called anymore so the instance doesnt exist.

I'm guessing I shouldn't be calling destroy function and the events still being fired is more of a big with handsontable or this maybe?

**Comment by budnix** [comment]
Hi, In 0.17.0-beta1 we introduce new service (`hotRegisterer`) to retrieve Handsontable instance. Check out this demo http://handsontable.github.io/ngHandsontable/demo/#/other-access-to-instance.
