### ISSUE TITLE
Mouseover and Mousewheel scroll errors in console

### ISSUE THREAD

**Issue by HandsTest** [handsontable/ngHandsontable#64]
Moving the mouse over the table produces errors in  console IE 11. In Chrome 42, MouseScroll on row header produces error, when the table cannot be scrolled anymore, like trying to scroll up.

![image](https://cloud.githubusercontent.com/assets/10513809/7296146/8a0ae332-e9da-11e4-895b-00af7807b70b.png)

![image](https://cloud.githubusercontent.com/assets/10513809/7296316/f2f6919c-e9db-11e4-8640-680ea5bf42fd.png)

**Comment by motin** [comment]
Same here on scroll OSX, Chrome 43, on http://handsontable.github.io/ngHandsontable/
https://www.dropbox.com/s/zzxnuewbvoh88ek/Screenshot%202015-06-05%2022.42.07.png?dl=0
Similar errors on Firefox "TypeError: event.path is undefined" on mouseover and scroll.
No errors when running vanilla handsontable.

**Comment by alaviamir** [comment]
I am getting the following issue when scrolling "mouseover" event:
Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.

I am getting this issue on 0.5.2, do you know if the behavior is any different on previous versions?

Thank you in advance!

**Comment by MMTLukas** [comment]
@alaviamir: I use currently nghandsontable 0.5.1 with handsontable 0.14.1 to avoid this error.

**Comment by alaviamir** [comment]
@MMTLukas Thank you very much! I will try this

**Comment by aendrew** [comment]
Experiencing this issue. Have tried downgrading ngHandsontable to 0.5.1 and handsontable to 0.14.1, no effect.

**Comment by alaviamir** [comment]
No luck here either @aendrew 
Please let me know what you find

**Comment by aendrew** [comment]
@alaviamir I just downgraded ngHandsontable to 0.5.1 (with handsontable 0.12.6) and that message has gone away — hurrah!

**Comment by sarahquigley** [comment]
I also get this same error on scroll with the mouse wheel (Chrome 43).

```
Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
```
Also using ngHandsontable 0.5.2 with handsontable 0.14.1. 

Wondering will this still be an issue when a release of ngHandsontable with compatibility with Handsontable 0.15.0 comes out? Perhaps worth investigating before such a release, and resolving if still an issue?

**Comment by cityhunterok** [comment]
same question in chrome 

Uncaught TypeError: Cannot read property 'indexOf' of undefinedWalkontableOverlays.translateMouseWheelToScroll @ handsontable.full.js:20760(anonymous function) @ handsontable.full.js:20713
2handsontable.full.js:20737 Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.(anonymous function) @ handsontable.full.js:20737callbackProxy @ handsontable.full.js:4681
handsontable.full.js:20760 Uncaught TypeError: Cannot read property 'indexOf' of undefinedWalkontableOverlays.translateMouseWheelToScroll @ handsontable.full.js:20760(anonymous function) @ handsontable.full.js:20713
2handsontable.full.js:207

**Comment by budnix** [comment]
Fixed in 0.6.0 version

**Comment by aendrew** [comment]
:+1: Working for me! Huge thanks!

**Comment by nkeeslin** [comment]
What version of handsontable are you guys using?  Because I'm still getting the same bug as @sarahquigley using ngHandontable 0.7.0 with handsontable 0.14.1.  But when i try to update my handsontable, it breaks.
