### ISSUE TITLE
Custom borders

### ISSUE THREAD

**Issue by Hubbee** [handsontable/ngHandsontable#65]
Custom borders doesn't work. 

Any plans to add this feature?

**Comment by gscoppino** [comment]
I have the same problem. Demo below:
http://jsfiddle.net/gscoppino/0j6cLpyt/

**Comment by homi2015** [comment]
Well it works right now with the ngHandsontable version 0.6.0. I have done the following in my sample.

Index.html:
<hot-table
    settings="{colHeaders: colHeaders, contextMenu: ['row_above', 'row_below', 'remove_row'], afterChange: afterChange }"
    rowHeaders="false"
    minSpareRows="minSpareRows"
    datarows="db.items"
    height="300"
    width="700"
    columns="db.columns"
    customBorders = "myBorders">
</hot-table>

And for the custom borders in my controller, I have the following:

$scope.myBorders = [
            {
	            range: {
	                    from: {
	                        row: 0,
	                        col: 0
	                    },
	                    to: {
	                        row: 2,
	                        col: 1
	                    }
	                },
	                top: {
	                    width: 2,
	                    color: 'red'
	                },
	                left: {
	                    width: 2,
	                    color: 'blue'
	                },
	                bottom: {
	                    width: 2,
	                    color: 'green'
	                },
	                right: {
	                    width: 2,
	                    color: 'yellow'
	                }
	            }
        	];

**Comment by AMBudnik** [comment]
Please follow the bug report at [list](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3A%22Plugin%3A+custom+borders%22) for updates
