### ISSUE TITLE
Call core methods?

### ISSUE THREAD

**Issue by tslater** [handsontable/ngHandsontable#68]
How can I all a core method using ngHandsontable? Is it possible?

ex. $('#id').handsontable('validateCells',function(){});

**Comment by tamonan** [comment]
Take a look to: https://github.com/handsontable/ngHandsontable/issues/34

Works for me, but I still can't invoke Utils method, DataMap for example.

**Comment by budnix** [comment]
In 0.17.0-beta1 you can use `hotRegisterer` service to get Handsontable instance (http://handsontable.github.io/ngHandsontable/demo/#/other-access-to-instance).
