### ISSUE TITLE
Is Rule.js and Formula.js available for ngHandsontable

### ISSUE THREAD

**Issue by jongravois** [handsontable/ngHandsontable#70]
Is Rule.js and Formula.js available for ngHandsontable?

**Comment by ensign-rbaker** [comment]
+1, would love to see an example of this if it does exist

**Comment by nani83** [comment]
formula not working; any workaround for this?

**Comment by Kritika2808** [comment]
+1, formula not working

**Comment by xfight0** [comment]
+1, formula not working

**Comment by CaioPaiola** [comment]
+1, formula not working

**Comment by AMBudnik** [comment]
RuleJS project has been held. Currently we provide the logic via formula-parser
