### ISSUE TITLE
oldvalue issue

### ISSUE THREAD

**Issue by victorsosa** [handsontable/ngHandsontable#71]
HI, 
I am getting this issue:
Error: oldValue is undefined

I can see the handsontable load without the data. I already try it using the jquery only version and it load fine with the data that I have; but when I changed to angularjs, it only load the table empty with the column title and that's it. 

Do I need to set anything else?

```
app = angular.module("Grades", ['ngResource', 'ngHandsontable'])

  $scope.searchGrades = ->
	  Notas.get({ano_escolar: $scope.ano_escolar, materia: $scope.materia, semestre: $scope.semestre, curso: $scope.curso, seccion: $scope.seccion, tanda: $scope.tanda}, (result, getResponseHeaders) -> 
	    $scope.resultData = result.aaData
	    console.log($scope.resultData))
```

```
	<div hot-table
	    settings="{colHeaders: colHeaders, contextMenu: ['row_above', 'row_below', 'remove_row'], afterChange: afterChange }"
	    datarows="resultData"
	    height="700"
	    width="700">

	    <hot-column data="matricula"       title="'Matricula'" type="grayedOut" readOnly></hot-column>
	    <hot-column data="semestre"        title="'Semestre'"  type="grayedOut"  readOnly></hot-column>
	    <hot-column data="materia"         title="'Materia'"   type="grayedOut"  readOnly></hot-column>
	    <hot-column data="ev1"             title="'EV1'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="ev2"             title="'EV2'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="ev3"             title="'EV3'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="ev4"             title="'EV4'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="examen"          title="'Examen'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="completivo"      title="'Completivo'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="extra"           title="'Extra'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="esp"             title="'Esp'" type="'numeric'" format="'000'"></hot-column>
	    <hot-column data="esp2"            title="'Esp2'" type="'numeric'" format="'000'"></hot-column>
	</div hot-table>
```

**Comment by victorsosa** [comment]
I think the problem is with this code recently added, What would happen if the oldValue is undefined, because this is suppose to be initialize the data?

```
					/***
					 * INITIALIZE DATA
					 */
					scope.$watch('datarows', function (newValue, oldValue) {
						if (oldValue.length == scope.htSettings.minSpareRows && newValue.length != scope.htSettings.minSpareRows) {
							scope.htSettings['data'] = scope.datarows;
							settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
						}
					});
```

**Comment by victorsosa** [comment]
right now the oldValue is undefined, I check the scope and it looks like there is nothing there... weird

**Comment by yfarrugia** [comment]
I had the same issue, I resolved it by checking whether the newValue is undefined then checking the length.In this case the oldValue argument would be redundant:

scope.$watch('datarows', function (newValue) {
 if (newValue != undefined && newValue.length != scope.htSettings.minSpareRows) {
  scope.htSettings['data'] = scope.datarows;
  settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
 }
});

**Comment by yfarrugia** [comment]
This is also a compatibility issue, as it works perfectly with Handsontable 0.14 but not with 0.15

**Comment by victorsosa** [comment]
yea, thanks, I read that in you issue; I will tested this and let you know, thank you.

**Comment by victorsosa** [comment]
there is a pull request to fix the 0.15 issue; check pull request #75

**Comment by yfarrugia** [comment]
I have further tested this and the issue persists using both versions 0.15 and 0.14 of Handsontable.
The work around I found is to check whether the newValue is undefined on ngHandsontable (Line: 265):

scope.$watch('datarows', function (newValue) {
if (newValue != undefined && newValue.length != scope.htSettings.minSpareRows) {
scope.htSettings['data'] = scope.datarows;
settingFactory.updateHandsontableSettings(scope.hotInstance, scope.htSettings);
}
});

I confirm public hooks Issue is resolved by #75

**Comment by victorsosa** [comment]
I did the change you suggest, the issue is gone, but still I can see the table loaded with the data and i don't see any error in the console

**Comment by hristod** [comment]
I've got the same issue. I am wondering, why it isn't happening in the example? When I put the example data and the example directive code, it's all working - no problems. When I try my own data, it fails...

**Comment by victorsosa** [comment]
I know that the Ng code is working because I made a request to load the data, I know that the data is not correctly setup into nghandsontable but the table should show up empty at least.

**Comment by victorsosa** [comment]
I fix this issue, it was JS code related; now the table is loading
