### ISSUE TITLE
Select options instead of autocomplete

### ISSUE THREAD

**Issue by Nishchit14** [handsontable/ngHandsontable#73]
Ex . autocomplete = [ hello, hello there , hello there anybody];

If cell has value "hello there anybody" then it doesnt show any value in dropdown because it is autocomplete.

For this purpose select option is helpful to select any value from dropdown.

**Comment by Oceanswave** [comment]
+1

**Comment by akoskm** [comment]
So there is no simple select feature, only autocomplete?

**Comment by AMBudnik** [comment]
Here is a select option : https://docs.handsontable.com/pro/1.17.0/demo-select.html (docs) and here is a working example https://jsbin.com/casogidoje/edit?html,js,output
