### ISSUE TITLE
Are Some options broken?

### ISSUE THREAD

**Issue by jaksmid** [handsontable/ngHandsontable#74]
Hi,

on your example http://handsontable.github.io/ngHandsontable/
the context menu is turned on , but it does not seem to work.

Also, the table cells does not behave like excel but rather html table.

Do I understand it incorrectly? It seems to work on the handsontable without angular.

Many thanks,
Jakub

**Comment by VackarAfzal** [comment]
Are you using Firefox by any chance?

**Comment by AMBudnik** [comment]
Tested with Firefox 41, Chrome 45 and Safari 9 all worked fine with `contextMenu` options.
Issue closed cause of lack of precise information.
