### ISSUE TITLE
ngHandsontable (Angular) + Rule Js Not Working

### ISSUE THREAD

**Issue by mkashifkhan** [handsontable/ngHandsontable#76]
With the angular version of handsontable, the formula of ruleJs is not working, any body have the same issue?

**Comment by nani83** [comment]
we have the same problem. formulas(RuleJS) not working; any work around for this.

**Comment by mkashifkhan** [comment]
@nani83 , we have solved this problem this way ,basically we need an actual table instance, there  scope attribute "hotInstance" which gives us internal table instance, although we added a new scope table instance to the ngHandsontable  directive. called "inst",

// how to use
<hot-table id="id" settings="chartSettingsJson" hotInstance="tableInstance">

In your own controller you just need to update the table instance. I wrote it in timeout for scope applying purposes.

$timeout(function(){
                    tableInstance.updateSettings({formulas: true});
                   tableInstance.render();
                },10);


it works fine

**Comment by anilarya** [comment]
@mkashifkhan :  How to get this tableInstance ?

**Comment by mkashifkhan** [comment]
from tag of hot-table, there is an attribute of of html tag, "hotInstance"

<div settings="" hotInstance ="tableIntance" >

**Comment by nani83** [comment]
Thanks for reply; 

I tried adding hotInstance attribute, and fetching the value in controller with 
var hotDiv=angular.element($("hot-table[hotInstance]"));
var hotInstance=hotDiv.isolateScope().hotInstance; //tried this, as I was not able to get tableInstance
hotInstance.updateSettings({formulas:true});
hotInstance.render();

but did not work out.

**Comment by mkashifkhan** [comment]
![table](https://cloud.githubusercontent.com/assets/8805458/9160589/e51fbd2c-3f54-11e5-9194-c36e7b1a619b.png)

You have to declare the tableInstance object in your own controller, like

$scope.tableInstance, 
then you have to bind it the hotInstance in hot-table tag which i have showed above,
hotInstance will be bound with the tableInctance, now you can get all functionality through tableInstance

**Comment by msrikant32** [comment]
Hello,
my code is look like this,still i am not able to  calculate the sum value. Can any one help me to sove this.

<script src= "http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
	<script src="handsontable.full.js" type="text/javascript"></script>		
		<link  href="handsontable.full.css" rel="stylesheet" type="text/css">
		<script src="angular.js" type="text/javascript"></script>		
		<script src="ngHandsontable.js" type="text/javascript"></script>
		<script>
	     var app = angular.module('myApp', ['ngHandsontable']);
	     app.controller('myCtrl', function($scope) {
	    	
	         $scope.tabledata=[	{a:'73903', b:'15015', c:'=SUM(A1:B1)'},
	                           	{a:'73904', b:'15013', c:'=SUM(A2:B2)'},
	                           	{a:'73905', b:'15014', c:'=SUM(A3:B3)'}
	                 			];
	         $scope.gridOptions = {
	        	        data: 'tabledata'
	        	      };
	         $timeout(function(){
	        	 tableInstance.updateSettings({formulas: true});
	        	 tableInstance.render();
	        	 },10);
	     });
		</script>
</head>
<body data-ng-app="myApp">
<h1>Addition</h1>
 						<div style="position: relative;" data-ng-controller="myCtrl">
              			<hot-table
              			hotInstance="tableInstance"
              			formulas="true"
              			colHeader="true"
			         	rowHeaders="false"
			         	contextMenu="false"
			         	datarows="tabledata"
			         	colWidths="[100,100,100]">
			         	<hot-column data="a" title="'A'" ></hot-column>
			         	<hot-column data="b" title="'B'"></hot-column>
			         	<hot-column data="c" title="'Total'"></hot-column>
              			</hot-table>
              			</div>
</body>
</html>

**Comment by msrikant32** [comment]
Output is comming like this

A               B            Total
73903	15015	=SUM(A1:B1)
73904	15013	=SUM(A2:B2)
73905	15014	=SUM(A3:B3)

**Comment by nani83** [comment]
It worked for me, after adding handsontable formula js; (I was not able to add to bower dependencies, instead, I added this one as one of the vendor dependencies, in main html)

All I did is,
.html
<hot-table datarows="someData" height="300"
            rowHeaders="false"
            minSpareRows="minSpareRows"
            >
            <hot-column data="col1" title="'Column 1'"></hot-column>
            <hot-column data="col2" title="'Column 2'"></hot-column>
        </hot-table>

controller.js
$timeout(function(){
var hotDiv=angular.element($("hot-table"));
var hotInstance=hotDiv.isolateScope().hotInstance; 
hotInstance.updateSettings({formulas:true});
hotInstance.render();
},10);

**Comment by homi2015** [comment]
I'm also facing an issue with formulas. Can you please your index.html file here? Need to check the js files you included

**Comment by Kritika2808** [comment]
Not working

**Comment by pdemilly** [comment]
Got it working. As explained by a few you need to apply some settings after the hot-table has been instantiated. This is how I did it in v0.7. 

In my controller I inject hotRegisterer   .controller('MainCtrl', $scope, $timeout, hotRegisterer)

then at the end of my controller, this is where I find my hot-instance and apply the settings

$timeout(function(){
                var spreadsheet = hotRegisterer.getInstance ('projections');
                spreadsheet.updateSettings({ formulas: true});
                spreadsheet.render();
        },10);

Then in my template I need to define a hot-id 'projections' in this case

<hot-table hot-id="projections" settings="settings" datarows="items" height="550">
</hot-table>

Hope it will help others. Only drawback is a little flickering as the table is first rendered with the formula and then they are converted. Haven't tried yet but I bet a little ng-show="!loading" could take care of that

Great lib by the way

**Comment by Kritika2808** [comment]
@pdemilly can u please tell, how to define hot-id, I am trying but not able to define id-
<hot-table
			    settings="{colHeaders: true, rowHeaders: true, fixedColumnsLeft: 1, contextMenu: ['col_left', 'col_right', 'remove_col', 'redo', 'undo'], colWidths:[200,75,75,75,75,75,75,75,75], mergeCells:[
			      {row: 5, col: 1, rowspan: 1, colspan: 8}, {row: 10, col: 1, rowspan: 1, colspan: 8}
				], minSpareRows: 0, comments: ''}" 
			    datarows="db" cells="cellSettings"  height="450"  width="880" columns=[{editor:false},{editor:'numeric',comments:''},{editor:'numeric',comments:''},{editor:'numeric',comments:''},{editor:'numeric',comments:''},{editor:'numeric',comments:''},{editor:'numeric',comments:''},{editor:'numeric',comments:''},{editor:'numeric',comments:''}] hot-id="projections"
			></hot-table>

**Comment by Kritika2808** [comment]
@pdemilly hey I defined formulas: 'true' in my controller like this-
$scope.init = function(){
      $scope.hotInstance = this;
      $scope.hotInstance.updateSettings({ formulas: true});
      $scope.hotInstance.render();    
    }

But still, formulas not working
Do I need to do something else

**Comment by jibsworld** [comment]
You can try this workaround (verified and working)
Simplified code:
```
// In controller
$scope.settings = {
	startRows: 16, startCols: 16, minSpareRows: 1,
	colHeaders: true, rowHeaders: true, contextMenu: true, outsideClickDeselects: false,
	manualColumnResize: true, manualRowResize: true,
	
	afterInit: function() {
		this.updateSettings({formulas: true});
	}
};
```

```
<!-- html page -->
<hot-table settings="settings" />
```

**Comment by srisaravanan99** [comment]
There is another angular workaround for this. This will extend the Handsontable settings prototype to make sure "formulas" flag is available when NgHandsOnTable receives the settings.

```
yourApp.run(['$state', '$rootScope', function ($state, $rootScope) {
        //Extending the Handsontable DefaultSettings prototype with formulas flag.
        //This code snippet will ensure the formulas flag present when ngHandsOnTable merges the scope settings with original HandsOnTable settings.
        if (Handsontable.DefaultSettings.prototype) {
            Handsontable.DefaultSettings.prototype.**formulas** = false; //by default
        }   
    }]);

And in your controller - 


$scope.Tablesettings = {
            //TABLE SETTINGS
            colHeaders: true,
            autoWrapRow: true,
            columnSorting: false,
            comments: false,
            **formulas: true** }
```
This worked for me.

**Comment by rahulsharma841990** [comment]
Hi, i am also not able to use formulas in handsontable:

`<hot-table settings="{formulas: true, colHeaders: columnsData, stretchH: 'all',filters: true,dropdownMenu: true,manualColumnMove: true, contextMenu: ['row_above', 'row_below', 'remove_row','---------','col_left','col_right','remove_col','---------','undo','redo','---------','make_read_only','alignment'], afterChange: afterChange}"
                           row-headers="false"
                           min-spare-rows="minSpareRows"
                           datarows="vm.items"
                           height="500"
                           width="1255">
                        <hot-column data='{{key}}' title="key" type="grayedOut"  ng-repeat="(key, item) in vm.items[0]"></hot-column>
                </hot-table>`

can any one please help me?

**Comment by AMBudnik** [comment]
RuleJS is no longer maintained.
