### ISSUE TITLE
TypeError: event.path is undefined in FF

### ISSUE THREAD

**Issue by troddick** [handsontable/ngHandsontable#77]
I'm trying to implement this in my code, and am getting this error which is referencing line 4593 in handsontable.full.js
'len = event.path.length;'

this error occurs everytime the mouse moves. At first, I thought it was something I'm doing wrong, but then I finally tested the demo page in Firefox (http://handsontable.github.io/ngHandsontable/), and sure enough, everytime I move the mouse, I get this error. I am using Firefox 38.0.5.

Any suggestions?
-- as a side note (may be related), I'm using a Dell touchscreen laptop.
Also, it works great in Chrome, and has the same error occurs in IE.

Thanks,
Tonia Roddick

**Comment by darkmavis1980** [comment]
+1 I have the same issue with handsontable 0.14.1 (the latest I can use with ngHandsontable as I'm using it for an angularjs project)

**Comment by darkmavis1980** [comment]
As far I can see the issue is caused by the line 4592 from this code
```javascript
event = Handsontable.Dom.polymerWrap(event);
```
which calls this function at line 3820
```javascript
Handsontable.Dom.polymerWrap = function(element) {
  /* global Polymer */
  return typeof Polymer !== 'undefined' && typeof wrap === 'function' ? wrap(element) : element;
};
```
Essentially on firefox this function doesn't convert the object into a Polymer object and returns the original  element, so essentially when at line 4593 we call this code
```javascript
len = event.path.length;
```
length is undefined simply because the `event.path` is not being created

**Comment by troddick** [comment]
I found a fix.
Change this: 
len = event.path.length;
to this:
len = event.path ? event.path.length : 0;

and now it works.

Tonia

**Comment by darkmavis1980** [comment]
Hi @troddick, at the end I found a much simpler solution as you can see [here](https://github.com/handsontable/ngHandsontable/issues/83), essentially I was calling the handsontable with the html element '<hot-table>' which is also used by the base package of handsontable as a **Polymer** element, so I just had to use the directive as an attribute like this:
```html
<div hot-table></div>
```
And now it works fine for me

**Comment by budnix** [comment]
Hi, We have released new version (https://github.com/handsontable/ngHandsontable/releases) which contains the newest version of Handsontable. This version should resolve all issues.
