### ISSUE TITLE
Using ng-model and ng-model-options in ngHandsontable

### ISSUE THREAD

**Issue by syedsuhail** [handsontable/ngHandsontable#78]
Hi,

I have a use case where my data needs to use the getterSetter of ng-model-options. While trying out I saw no option to bind for ng-model. Also is there any way to get each item of the data row?

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
