### ISSUE TITLE
Moving column doesn't change renderers order

### ISSUE THREAD

**Issue by lukaszblacha** [handsontable/ngHandsontable#8]
I don't know yet if it's handsontable or angular-ui-handsontable bug, there is no example of moving columns with custom renderers in handsontable.

**Comment by AMBudnik** [comment]
Hi @lukaszblacha I made [this simple example](http://jsbin.com/wubazawezu/edit?html,js,output) for this issue. It's a saveHTML renderer and it works after moving columns also.

Issue will stay closed as long as this functionality works fine but if you would have any problems please let us know.
