### ISSUE TITLE
Plans to support Handsontable 0.15.0

### ISSUE THREAD

**Issue by sarahquigley** [handsontable/ngHandsontable#80]
I have noticed that the latest ngHandsontable release 0.5.2 is not compatible with Handsontable 0.15.0. (It works perfectly with Handsontable 0.14.1). (Using them together causes the error described here: https://github.com/handsontable/ngHandsontable/issues/79) I am eager to upgrade a project I am working on to Handsontable 0.15.0, but doing so is blocked by our dependency on ngHandsontable. 

When can a new release of ngHandsontable be expected, one with support for Handsontable 0.15.0?

Many thanks!

**Comment by darkmavis1980** [comment]
+1

**Comment by prabhuish** [comment]
+1

**Comment by HandsTest** [comment]
+1

**Comment by lukax** [comment]
+1

**Comment by budnix** [comment]
Released in 0.6.0 version which is compatible with Handsontable 0.16.0

**Comment by darkmavis1980** [comment]
Great! I'll test tomorrow and see how it goes on our project
