### ISSUE TITLE
Scrollbar not working in ie11

### ISSUE THREAD

**Issue by sungdv** [handsontable/ngHandsontable#82]
scrollbar not working in ie11 ( using handsontable is OK )
![ng-handsontable-ie11](https://cloud.githubusercontent.com/assets/12620939/8491023/3ab8b612-216e-11e5-9c50-7e5eb2cde45b.jpg)

but in chrome is OK
![ng-handsontable-chrome](https://cloud.githubusercontent.com/assets/12620939/8491029/4677885c-216e-11e5-8d41-91a9861b6600.jpg)

**Comment by AMBudnik** [comment]
The issue is related to vanilla version. Please track changes to the following [issue board](https://github.com/handsontable/handsontable/issues?q=is%3Aopen+is%3Aissue+label%3AIE%2FEdge)
