### ISSUE TITLE
Restrict copy paste across columns

### ISSUE THREAD

**Issue by sagar-k** [handsontable/ngHandsontable#85]
Can anyone provide a way to restrict copy paste across columns(i.e copy from one column and paste in other column should not be allowed)

**Comment by markusp72** [comment]
+1
(option to limit copy/paste, e.g., for read-only columns, could be useful under certain circumstances)

**Comment by AMBudnik** [comment]
Hi @sagar-k maybe this one would help https://docs.handsontable.com/0.22.0/Options.html#skipColumnOnPaste

**Comment by markusp72** [comment]
helpful indeed. tx.
