### ISSUE TITLE
Not working in Safari (http://handsontable.github.io/ngHandsontable/)

### ISSUE THREAD

**Issue by aarele** [handsontable/ngHandsontable#89]
Apparently the angular version is not working in Safari. The grids appear as just readonly tables.
Please use below url to check 
http://handsontable.github.io/ngHandsontable/

**Comment by asadabbas88** [comment]
having same issue .. any idea what can be done for it?

**Comment by aarele** [comment]
Not sure. I havn't found anything till yet. But something tell me that it sould work as as Non-Angular version of Handson is working on Safari as well.

**Comment by mmealling** [comment]
Did anyone find out what's up with Safari? This problem just hit me as well...

**Comment by swardi** [comment]
Angular version of HandsOnTable doesn't work on safari, it displayed only readonly table. You cannot edit by clicking on the cells.

**Comment by AMBudnik** [comment]
I couldn't replicate the issue. The issue will be closed but feel free to leave a comment if the bug still exists
