### ISSUE TITLE
how to provide the source of the autocomplete

### ISSUE THREAD

**Issue by vincentzhou2013** [handsontable/ngHandsontable#9]
I saw one in the demo, 
{value: 'item.Product.Description', type: 'autocomplete', title: 'Favorite food', width: 120, clickrow: 'item.Product.Description = option.Description', optionList: 'option in item.Product.Options', optionTemplate: '<img ng-src="{{option.Image}}" style="width: 16px; height: 16px; border-width: 0"> {{option.Description}}'},
    
but I cannot fingure out how to do my own. mine is simple, pick up a number from 1~ 9, I tried below, but it doesn't work. 
{value: 'item.Id', title: 'Id',type: 'autocomplete',source: '["1","2","3","4","5","6","7"]'},  
any help is appreciated.

**Comment by steveed** [comment]
I defined my columns and headers in the scope and I set the value of the autocomplete like this:

     {
        data: 'id',
        type: 'autocomplete',
        width: 120,
        optionList: {object: [1'', '2', '3', '4']},
        strict: true
    },

Seems to be working fine now, I don't think this is the way it should be done but it is working.

**Comment by tslater** [comment]
@steveed could you post a larger example of all your columns and the directive instance itself?

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity and author's reply.
