### ISSUE TITLE
Autocomplete not working in v 0.15.1

### ISSUE THREAD

**Issue by pillaiv** [handsontable/ngHandsontable#90]
I have spent quite a bit of time and below does not work.

``` html
 <hot-column data="Currency" title="'Currency'" type="'autocomplete'">
                    <hot-autocomplete datarows="USD,EUR,TRY,TWO"></hot-autocomplete>
                </hot-column>

or 

assiging the values to scope also does not work either.

    $scope.currencyList = "USD, EUR, TRY, TWO";

"  <hot-column data="Currency" title="'Currency'" type="'autocomplete'">
                    <hot-autocomplete datarows=""></hot-autocomplete>
                </hot-column>"


```

I get the below error for both 

Uncaught TypeError: Cannot read property '1' of undefined

![image](https://cloud.githubusercontent.com/assets/7011974/8593929/287e4ac8-2634-11e5-859f-6d663c5eb55d.png)

**Comment by teegh** [comment]
How about bellow? 

```javascript
$scope.currencyList = [{
    "Currency":"100",
    "autocomplete" : [{"ac":"USD"}, {"ac":"EUR"}, {"ac":"TRY"}, {"ac":"TWO"}]
}];
```

```html
<hot-table datarows="currencyList">
  <hot-column data="Currency" title="'Currency'" type="'autocomplete'">
     <hot-autocomplete datarows="ac in autocomplete"></hot-autocomplete>
  </hot-column>
</hot-table>
```

**Comment by pillaiv** [comment]
Hi, thanks but I cannot have <hot-table datarows="currencyList"> because it will be 
<hot-table datarows="datarows"> . this datarows is set in my controller js $scope.datarows = response.data;

So only way is as below 

     '<hot-table settings="{colHeaders: colHeaders, contextMenu: ['row_above', 'row_below', 'remove_row'], afterChange: afterChanges,search : true }"
                       rowheaders="false"
                       minsparerows="minSpareRows"
                       observechanges="true"
                       datarows="datarows"
                       columns="dataColumns"
                       height="750">

                <hot-column data="ProNumber" title="'Pro Number'" width="100"></hot-column>
        <hot-column data="ProductName" title="'Product Name'" width="100"></hot-column>
  <hot-column data="currencyList" title="'Currency Iso Code'" type="'autocomplete'">
                    <hot-autocomplete datarows="ac in autocomplete"></hot-autocomplete>
                </hot-column>
  <hot-column data="DummyBoolColumn" title="'DummyBoolColumn'" type="'checkbox'"></hot-column>
            </hot-table>

**Comment by AMBudnik** [comment]
Sorry that there was no reply for a longer time.
I am sure that you have already finished the project or abandoned it so I am closing the issue. However if not I'll reopen the issue.
