### ISSUE TITLE
Can ngHandsontable 0.6.0 add copy-paste context menu ?

### ISSUE THREAD

**Issue by teegh** [handsontable/ngHandsontable#92]
Hi, I am very grateful to ngHandsontable　0.6.0. I have some questions. Can ngHandsontable 0.6.0 add copy-paste context menu ? I don't know how to add a contextMenuCopyPaste config item.

I can do the same it?
http://docs.handsontable.com/0.16.0/demo-context-menu.html
> ### Copy-paste configuration
> To configure Handsontable to use this plugin you need to add a contextMenuCopyPaste config item to your Hansontable instance.

**Comment by budnix** [comment]
Hi, of course you can add copy/paste to context menu. Here’s the working demo http://handsontable.github.io/ngHandsontable/demo/#/plugins-copy-paste-context-menu (v0.7.0).

**Comment by teegh** [comment]
@budnix  Thank you very much for the information.
