### ISSUE TITLE
Add and Delete columns on demand

### ISSUE THREAD

**Issue by homi2015** [handsontable/ngHandsontable#93]
How do we add and remove columns as and when required on ngHandsontable? I don't want to do it via context menu but rather dynamically through button click. I looked at the documentation for "alter" and "updateSettings" methods but couldn't figure how to do it. Please find below my sample plunker

http://plnkr.co/edit/uStWAU?p=preview

If you can provide a sample it would be great

**Comment by motin** [comment]
+1

**Comment by miyura** [comment]
Try this:

http://plnkr.co/edit/spd2LG1cNZ0DdRSvo6h1?p=preview

**Comment by budnix** [comment]
Hi, In 0.17.0-beta1 we rewritten code and fixed a lot of bugs. From now addding/deleting columns on demand should be working well. Here's the working demo http://handsontable.github.io/ngHandsontable/demo/#/columns-add-remove-column-ng-repeat or http://handsontable.github.io/ngHandsontable/demo/#/columns-add-remove-column-by-attr.

**Comment by homi2015** [comment]
Thanks for the example. It is working as desired.
