### ISSUE TITLE
Cannot change data in table after loading it

### ISSUE THREAD

**Issue by Mintas** [handsontable/ngHandsontable#97]
My columns are not ReadOnly, i can click on them and write new value into. But after this cell value returns to loaded state with no changes displayed. 
How to fix it?
updated: Bug takes it place only if maxRows parameter is set.

**Comment by benjamingarcia** [comment]
:+1:

**Comment by kotmatpockuh** [comment]
+1

**Comment by AMBudnik** [comment]
Can you share a demo where is issue is replicable? Which Handsontable version are you loading?
