### ISSUE TITLE
Stretch issue

### ISSUE THREAD

**Issue by crash21** [handsontable/ngHandsontable#98]
Hello,

I am using this config:

```
<div hot-table
    stretchH= "all"
    settings="{contextMenu: ['row_above', 'row_below', 'remove_row'] }"
    rowHeaders="false"
    minSpareRows="10"
    datarows="gridData">
</div>
```

Unfortunately stretching is not working. Is there something wrong I am doing or is there a workaround to ,make it work?

**Comment by krzysztofspilka** [comment]
@crash21 could report this in the hot-table repository issue board?

**Comment by misaunde** [comment]
+1

**Comment by mathiasconradt** [comment]
You need to do it like this:

stretch-h="'all'"

Note: `stretch-h` instead of camel-case and put the `'all'` in apostrophes.
Nevertheless, there are still other issues with this. See https://github.com/handsontable/handsontable/issues/2831

**Comment by AMBudnik** [comment]
the related issue has been fixed https://github.com/handsontable/handsontable/issues/2831

**Comment by jnjagtap** [comment]
how to resize row/column on fix rows/column in this?

**Comment by AMBudnik** [comment]
Hi @jnjagtap 
here's a demo with `manualColumnResize` and `fixedColumnLeft` enabled http://jsbin.com/sodiyikawa/edit?html,js,output
